---
- name: "Copy systemd service {{ ipv6_systemd_service_name }}"
  become: true
  ansible.builtin.template:
    src: "{{ ipv6_systemd_service_name }}.j2"
    dest: "/etc/systemd/system/{{ ipv6_systemd_service_name }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart and enable new ipv6 addr service
