---
- name: restart ssh daemon
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true



- name: dpkg-reconfigure keyboard-configuration
  command: /usr/sbin/dpkg-reconfigure -f noninteractive keyboard-configuration
  become: true
  when: ansible_os_family == 'Debian'
