---
- name: Install Python and tools
  block:
    - name: '[Debian/Ubuntu]'
      ansible.builtin.apt:
        update_cache: true
        name:
          - python3-full
          - python3-pip
        state: present
      when: ansible_facts.os_family != 'Darwin'
    - name: '[Darwin / Debian/Ubuntu]'
      ansible.builtin.package:
        name:
          - pipx
      become: "{{ 'true' if ansible_facts['os_family'] != \"Darwin\" else 'false' }}"
    - name: '[Darwin]'
      community.general.homebrew:
        name:
          - python
      become: false
      when: ansible_facts.os_family == 'Darwin'
  become: true


- name: Update alternatives
  block:
    - name: Switch to python3
      community.general.alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3

    - name: Switch to pip3
      community.general.alternatives:
        name: pip
        link: /usr/bin/pip
        path: /usr/bin/pip3
  become: true
  when: ansible_facts.os_family != 'Darwin'
