---
- name: Install tmux
  apt:
    name:
      - tmux
    state: present

- name: Copy config file
  copy:
    src: 'tmux.conf'
    dest: '/home/{{ username }}/.tmux.conf'
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: 0644
