---
- name: Get username of current user
  changed_when: false
  become: false
  run_once: true
  shell: whoami
  register: username

- name: Get uid of current user
  changed_when: false
  become: false
  run_once: true
  shell: id -u
  register: uid

- name: Get gid of current user
  changed_when: false
  become: false
  run_once: true
  shell: id -g
  register: gid

- name: Get gid of the docker group
  changed_when: false
  become: false
  run_once: true
  shell: >
            getent group |
            grep docker |
            awk -F: '{printf "%d", $3}'
  register: docker_gid

# ALTERNATIVE 4 username: `id -u -n`
- name: Set variables
  run_once: true
  become: false
  set_fact:
                 #ansible_user_id
    user_name={{ username.stdout }}
    user_uid={{ uid.stdout }}
    user_gid={{ gid.stdout }}
    docker_gid={{ docker_gid.stdout }}


#-  ansible.builtin.debug:
#    msg: user_name={{ user_name }}, user_uid={{ user_uid }}, docker_gid={{ docker_gid }}
