---
- include_tasks: ssh.yml

- name: Install login system stats script
  copy:
    src: "10-show_system_info"
    dest: "/etc/profile.d/10-show_system_info"
    owner: "root"
    group: "root"
    mode: 0755
