---
#- name: Add ssh key for {{ user_name }}
#  authorized_key:
#    user: {{ user_name }}
#    key: {{ user_ssh_key }}


- name: Disable SSH root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - restart ssh daemon

- name: Enable SSH public key authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: "PubkeyAuthentication yes"
    state: present
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - restart ssh daemon

- name: Disable SSH password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '{{ item.regex }}'
    line: '{{ item.line }}'
    validate: '/usr/sbin/sshd -T -f %s'
  with_items:
    - { regex: "^#?PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regex: "^#?ChallengeResponseAuthentication", line: "ChallengeResponseAuthentication no" }
  notify:
    - restart ssh daemon

- name: Change SSH port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port 2233"
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - restart ssh daemon
