---
- name: Copy docker daemon IPv6 config file
  ansible.builtin.copy:
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:abc1::/64"
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart docker daemon

# Command: `docker network create --subnet="2001:db8:1::/64" --ipv6 traefik`
- name: Create a network w/ IPv6 IPAM config
  community.docker.docker_network:
    name: '{{ docker_default_network }}'
    enable_ipv6: true
    ipam_config:
      - subnet: 2001:db8:1::/64


# Fix routing (since we use internally private IPv6 addresses which are NOT routable)
# VALIDATION: `docker run --network=reverse_proxy --rm -t busybox ping6 -c 4 google.com`
# $$$$$$$$$$$$$$    WORKAROUND since ansible iptables doesn't seem 2 support masquerade ??!!    $$$$$$$$$$$$$$
# `ip6tables -t nat -A POSTROUTING -s 2001:db8:1::/64 ! -o docker0 -j MASQUERADE`
#- name: Routing for bridge network
#  ansible.builtin.iptables:
#    comment: IPv6 routing for docker's bridge network
#    ip_version: ipv6
#    table: nat
#    action: append
#    chain: POSTROUTING
#    source: 2001:db8:abc1::/64 !
#    out_interface: docker0
#    state: present
# `ip6tables -t nat -A POSTROUTING -s 2001:db8:1::/64 ! -o docker0 -j MASQUERADE`
# sudo sh -c "ip6tables-save > /etc/iptables/rules.v6"
- name: Install iptables
  ansible.builtin.apt:
    name:
      - iptables
      - iptables-persistent
    state: present
  become: true

- name: Copy iptable config tables
  ansible.builtin.copy:
    src: rules.v6
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart networking daemon
