---
- name: Install dependencies required for Firefox config
  ansible.builtin.pip:
    name:
      - requests

- name: "Workaround (since `include_role` doesn't accept `become`)"
  block:
    - name: Run firefox config role
      ansible.builtin.include_role:
        name: staticdev.firefox
  become: false

- name: 'Copy default suggested bookmarks  (TODO: AUTO IMPORT  !!)'
  ansible.builtin.copy:
    src: firefox-dev_bookmarks.json
    dest: '/home/{{ user_name }}/.firefox-default_dev_bookmarks.json'
  become: false


- name: Autostart Firefox on login
  ansible.builtin.file:
    src: /usr/share/applications/{{ firefox_package_name }}.desktop
    dest: '/home/{{ user_name }}/.config/autostart/{{ firefox_package_name }}.desktop'
    state: link
  become: false
