---
- name: Set GNOME settings
  block:
    - name: Install config tools
      ansible.builtin.apt:
        name:
          - dconf-editor
          - gnome-shell-extensions
          #- gnome-tweak-tool
        state: present

    # HOW2: gesettings tool  (e.g., `gsettings get org.gnome.desktop.input-sources sources`); example: https://gist.github.com/carlwgeorge/c560a532b6929f49d9c0df52f75a68ae
    - name: GNOME - Set settings
      community.general.dconf:
        key: '{{ gnome_setting.key }}'
        value: '{{ gnome_setting.value }}'
        state: '{{ gnome_setting.state }}'
      with_items:
        # !!  BE AWARE: Schema for gtk (used by `gsettings`): `org.gtk.Settings.FileChooser` vs. Path (used by dconf editor and Ansible module): `org.gtk.settings.file-chooser`  !!
        # --  General settings  --
    #    - { key: '/org/gnome/desktop/input-sources/sources', value: "[('xkb', 'de')]", state: present }
        # --  General UI  --
        - { key: '/org/gnome/desktop/session/idle-delay', value: 'uint32 0', state: present }
        - { key: '/org/gnome/desktop/interface/clock-format', value: "'12h'", state: present }
        - { key: '/org/gtk/settings/file-chooser/clock-format', value: "'12h'", state: present }
        - { key: '/org/gnome/desktop/wm/preferences/button-layout', value: "'close,minimize,maximize:'", state: present }
        - { key: '/org/gnome/shell/extensions/ding/show-home', value: 'false', state: present }
        - { key: '/org/gnome/shell/extensions/ding/show-trash', value: 'false', state: present }
        # --  Dock  --
        - { key: '/org/gnome/shell/extensions/dash-to-dock/extend-height', value: 'false', state: present }
        - { key: '/org/gnome/shell/extensions/dash-to-dock/dock-position', value: "'LEFT'", state: present }
        - { key: '/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size', value: '25', state: present }
        - { key: '/org/gnome/shell/extensions/dash-to-dock/dock-fixed', value: 'true', state: present }

        - { key: '/org/gnome/shell/favorite-apps', value: "[{{ dock_favorite_apps|join(', ') }}]", state: present }  # NOTE: Desktop entries for application (.desktop files) reside in '/usr/share/applications/' or '/usr/local/share/applications/'

        # --  Nautilus  --
        - { key: '/org/gnome/nautilus/preferences/show-delete-permanently', value: 'true', state: present }
        - { key: '/org/gnome/nautilus/preferences/default-sort-order', value: "'type'", state: present }         # Possible values: size, type, mtime, atime, starred
        - { key: '/org/gnome/nautilus/preferences/default-sort-in-reverse-order', value: 'false', state: present }
        - { key: '/org/gnome/nautilus/preferences/default-folder-viewer', value: "'list-view'", state: present } # Possible values: icon-view, list-view
        - { key: '/org/gnome/nautilus/list-view/default-zoom-level', value: "'small'", state: present }
        - { key: '/org/gnome/nautilus/list-view/default-visible-columns', value: "['name', 'type', 'size', 'date_modified']", state: present }
        - { key: '/org/gnome/nautilus/list-view/use-tree-view', value: 'true', state: present }
        - { key: '/org/gtk/settings/file-chooser/show-hidden', value: 'true', state: present }
      loop_control:
        loop_var: gnome_setting
      become: false
  when: "'GNOME' in desktop_envs"



- name: gdm3 - Enable Autologin
  block:
    - name: Check whether gdm3 is used
      ansible.builtin.package_facts:
        manager: auto

    - name: 'Enable autologin for {{ user_name }}'
      block:
        - name: Set autologin config file
          ansible.builtin.set_fact:
            gdm3_config_file: "{{ 'daemon.conf' if ansible_facts.distribution == 'Debian' else 'custom.conf' }}"
          become: false

        - name: Update config file
          ansible.builtin.replace:
            path: '/etc/gdm3/{{ gdm3_config_file }}'
            # UNMATCH IF NAME is already contained: '^(#\s*|\s*)AutomaticLoginEnable\s*=\s*(true|false)\n^(#\s*|\s*)AutomaticLogin\s*=\s*(?!{{ user_name }}$)\w+$'  (doesn't work -- PROBLEM: name unmatches, which causes it not to be updated if it's commented out)
            regexp: '^#\s*AutomaticLoginEnable\s*=\s*(true|false)\n^#\s*AutomaticLogin\s*=\s*\w+$'
            replace: |
              AutomaticLoginEnable = true
              AutomaticLogin = {{ user_name }}
      when: "'gdm3' in ansible_facts.packages"
