---
- name: Install dependencies required for Firefox config
  ansible.builtin.pip:
    name:
      - requests

- name: "Workaround (since `include_role` doesn't accept `become`)"
  block:
    - name: Run firefox config role
      ansible.builtin.include_role:
        name: staticdev.firefox
  become: false
