---
- name: Install Desktop environment
  block:
    - name: '[Debian]'
      ansible.builtin.apt:
        name:
#          - tasksel
          - gdm3
          - gnome-session
        state: present
      when: ansible_facts.distribution == 'Debian'
    - name: '[Ubuntu Server]'
      block:
        - name: Gather package facts
          ansible.builtin.package_facts:
            manager: auto
        - name: Install
          ansible.builtin.apt:
            name:
              - gdm3            # Display Manager
              - ubuntu-desktop
              # TODO: vanilla-gnome-desktop vanilla-gnome-default-settings
            state: present
          when: "'ubuntu-desktop' in ansible_facts.packages"
  become: true

- ansible.builtin.include_tasks: '{{ included_workstation_task }}'
  loop:
    - packages.yml
    - config-ui.yml
    - config-firefox.yml
  loop_control:
    loop_var: included_workstation_task
