---
# apt -- show installed packages: `apt list --installed`
# ---------------------------------------------------------
- name: Remove unncessary game packages
  ansible.builtin.apt:
    name:
      - aisleriot
      - gnome-mahjongg
      - gnome-mines
      - gnome-sudoku
    state: absent
    autoremove: true
    purge: true
  when: ansible_facts.distribution == "Ubuntu"

# TODO:  Cleanup Ubuntu distro
- name: Uninstall stuff which may be useful
  ansible.builtin.apt:
    name:
      - libreoffice
    state: present
  when: ansible_facts.distribution == "Ubuntu"
# ---------------------------------------------------------


- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist
    autoremove: true
    allow_downgrade: yes

- name: Install CLI tools
  ansible.builtin.apt:
    name:
      - trash-cli
    state: present

- name: Install media tools
  ansible.builtin.apt:
    name:
      - celluloid
      - vlc
    state: present

- name: Install LaTex
  ansible.builtin.apt:
    name:
      - texlive-full
      - texmaker
    state: present

- include_tasks: '{{ item }}'
  loop:
    - package-brave.yml
    - package-firefox.yml
    - package-codium.yml
    - package-conky.yml
    - package-nala.yml
