---
# --  Install Firefox  --
# TODO: (CURRENTLY 4 UBUNTU: temporary workaround to ensure on Ubuntu apt-version gets installed (better performance + 3rd party integrations like video download plugins))  --
- name: 'Ubuntu - Ensure no Firefox snap is / will be installed'
  block:
    - name: Add apt repo and update cache
      # NOTE: Equivalent command: `sudo add-apt-repository 'ppa:mozillateam/ppa'`
      ansible.builtin.apt_repository:
        repo: ppa:mozillateam/ppa
        state: present
        update_cache: true

    # CHECK via: `apt-cache policy`  ('Pin-Priority': https://wiki.ubuntuusers.de/Apt-Pinning/#Werte-fuer-Pin-Priority)
    - name: Pin apt repo
      ansible.builtin.template:
        src: snapd-exclude-firefox.pref.j2           # TODO: INLINE ONCE SUPPORTED BY MODULE
        dest: /etc/apt/preferences.d/snapd-exclude-firefox.pref
        owner: root
        group: root
        mode: 0644

    #TODO -- UNATTENDED UPGRADES: echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
  when: ansible_facts.distribution == 'Ubuntu'
  become: true


- name: Firefox - Install
  ansible.builtin.apt:
    name: '{{ firefox_package_name }}'
    state: present
    allow_downgrade: true
  become: true
