---
# apt -- show installed packages: `apt list --installed`
# ---------------------------------------------------------
- name: '[Debian/Ubuntu] Uninstall unncessary apt packages (mostly Gnome stuff)'
  ansible.builtin.apt:
    name:
      # Games
      - aisleriot
      - gnome-mahjongg
      - gnome-mines
      - gnome-sudoku
      - gnome-2048
      - gnome-chess
      - five-or-more
      - four-in-a-row
      - hitori
      - gnome-klotski
      - lightsoff
      - gnome-nibbles
      - quadrapassel
      - gnome-robots
      - swell-foop
      - iagno
      - tali
      - gnome-taquin
      - gnome-tetravex
      # Apps
      - gnome-clocks
      - gnome-calendar
      - gnome-contacts
      - gnome-documents
      - '*gnome-todo*'
      - gnome-maps
      - gnome-music
      - '*rhythmbox*'
      - gnome-weather
      - transmission*
      - libreoffice*
      # Media player
      - totem
      # Mail
      - evolution
      - thunderbird*
      - simple-scan
      # NOTE: 'cheese-common', 'libcheese-gtk25' & 'libcheese8' are required by the Settings app (package 'unity-control-center')
      - cheese
      - 'shotwell*'
    state: absent
    purge: true
    clean: true
    autoremove: true
  when: ansible_facts.os_family == 'Debian'

- name: '[Ubuntu] Uninstall unncessary apt packages (rmv snap store)'
  community.general.snap:
    name: snap-store
    state: absent
  become: true
  when: ansible_facts.distribution == 'Ubuntu'
# ---------------------------------------------------------


- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist
    clean: true
    autoremove: true

- name: Install CLI tools
  ansible.builtin.apt:
    name:
      - trash-cli
    state: present

- include_tasks: '{{ item }}'
  loop:
#    - package-kitty.yml
    - package-firefox.yml
    - package-brave.yml
    - package-codium.yml
    - package-conky.yml
    - package-flatpak.yml


- name: Unintall GNOME Terminal (got replaced by Kitty)
  ansible.builtin.apt:
    name: gnome-terminal
    state: absent


# TODO:  REVISE
- name: 'TEMPORARY WORKAROUND (since no windows buttons for kitty): Install termiantor'
  ansible.builtin.apt:
    name: terminator
    state: present
