---
# --  Install firefox  --
# ------------------------------- Ubuntu specific --------------------------------
# (CURRENTLY 4 UBUNTU: temporary workaround to ensure on Ubuntu apt-version gets installed (better performance + 3rd party integrations like video download plugins))  --
- name: 'Firefox - [Ubuntu] Remove snap'
  community.general.snap:
    name: firefox
    state: absent
  become: true
  when: ansible_facts.distribution == 'Ubuntu'

- name: '[Ubuntu] Firefox - Add apt repo and update cache'
  ansible.builtin.apt_repository:
    repo: ppa:mozillateam/ppa
    state: present
    update_cache: true
  become: true
  when: ansible_facts.distribution == 'Ubuntu'
  register: result_firefox_repo

#TODO -- UNATTENDED UPGRADES: echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox

# CHECK via: `apt-cache policy`  ('Pin-Priority': https://wiki.ubuntuusers.de/Apt-Pinning/#Werte-fuer-Pin-Priority)
- name: 'Firefox - [Ubuntu] Pin apt repo'
  ansible.builtin.copy:
    content: |
      Package: *
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/mozilla-firefox
    owner: root
    group: root
    mode: 0644
  become: true
  when: ansible_facts.distribution == 'Ubuntu'
# --------------------------------------------------------------------------------

- name: Firefox - Set package name
  ansible.builtin.set_fact:
    firefox_package_name={{ 'firefox-esr' if ansible_facts.distribution == 'Debian' else 'firefox' }}
  become: false

- name: Firefox - Install it
  ansible.builtin.apt:
    name: '{{ firefox_package_name }}'
    state: present
  become: true



# --  Configure Firefox  --
# TODO: firefox config
