---
# apt -- show installed packages: `apt list --installed`
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: true
    autoremove: true


- name: Install CLI tools
  ansible.builtin.apt:
    name:
      - trash-cli
    state: present

- name: Install media tools
  ansible.builtin.apt:
    name:
      - celluloid
      - vlc
    state: present

- include_tasks: '{{ item }}'
  loop:
    - package-brave.yml
    - package-firefox.yml
    - package-codium.yml
    - package-conky.yml
    - package-nala.yml


# ---------------------------------------------------------
- name: Remove unncessary game packages
  ansible.builtin.apt:
    name:
      - aisleriot
      - gnome-mahjongg
      - gnome-mines
      - gnome-sudoku
    state: absent
  when: ansible_facts.distribution == "Ubuntu"
