---
- name: Install conky
  ansible.builtin.apt:
    name: conky
    state: present

- name: Copy config file
  become: false
  ansible.builtin.copy:
    src: 'conky-config'
    dest: '/home/{{ user_name }}/.conkyrc'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644

- name: Create autostart dir
  become: false
  ansible.builtin.file:
    path: '/home/{{ user_name }}/.config/autostart/'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0755

- name: Create autostart entry
  become: false
  ansible.builtin.copy:
    src: 'conky-autostart-entry'
    dest: '/home/{{ user_name }}/.config/autostart/conky.desktop'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
