---
# apt -- show installed packages: `apt list --installed`
# ---------------------------------------------------------
- name: Uninstall unncessary apt packages (mostly Gnome stuff)
  ansible.builtin.apt:
    name:
      - aisleriot
      - gnome-mahjongg
      - gnome-mines
      - gnome-sudoku
      - gnome-calendar
      - '*gnome-todo*'
      - thunderbird*
      - transmission*
      - libreoffice*
      - '*rhythmbox*'
      - '*totem*'
      - simple-scan
      - '*cheese*'
      - 'shotwell*'
    state: absent
    purge: true
    clean: true
    autoremove: true
  when: ansible_facts.distribution == 'Ubuntu'
# ---------------------------------------------------------


- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist
    clean: true
    autoremove: true

- name: Install CLI tools
  ansible.builtin.apt:
    name:
      - trash-cli
    state: present

#- name: Install media tools
#  ansible.builtin.apt:
#    name:
#      - celluloid
#      - vlc
#    state: present

- name: Install LaTex
  ansible.builtin.apt:
    name:
      - texlive-full
      - texmaker
    state: present

- include_tasks: '{{ item }}'
  loop:
    - package-firefox.yml
    - package-brave.yml
    - package-codium.yml
    - package-conky.yml
