---
# apt -- show installed packages: `apt list --installed`
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: true
    autoremove: true


- name: Install CLI tools
  ansible.builtin.apt:
    name:
      - trash-cli
    state: present

- name: Install media tools
  ansible.builtin.apt:
    name:
      - celluloid
      - vlc
    state: present

- include_tasks:
  - package-brave.yml
  - package-codium.yml
  - package-conky.yml
  - package-nala.yml




#  aisleriot when: ansible_facts.os_family == "Ubuntu"
