---
- name: VSCodium - Add apt signing key
  # NOTE: Equivalent command: `wget -O - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | sudo apt-key add -`; Show keys: `apt-key list`
  ansible.builtin.apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    keyring: /usr/share/keyrings/vscodium-archive-keyring.gpg
    state: present
  become: true

- name: VSCodium - Add apt repo and update cache
  # NOTE: Equivalent command: `sudo add-apt-repository 'deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse'`
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs vscodium main'
    filename: vscodium.list
    state: present
    update_cache: true
  become: true

# CHECK via: `apt-cache policy`  ('Pin-Priority': https://wiki.ubuntuusers.de/Apt-Pinning/#Werte-fuer-Pin-Priority)
- name: VSCodium - Pin apt repo
  ansible.builtin.template:
    src: vscodium.pref.j2           # TODO: INLINE ONCE SUPPORTED BY MODULE
    dest: /etc/apt/preferences.d/vscodium.pref
    owner: root
    group: root
    mode: 0644
  become: true

- name: VSCodium - Install it
  ansible.builtin.apt:
    name: codium
    state: present
  become: true
