---
# Enables TRIM support via UASP    (validate: `lsusb -t` -> check whether "Driver" is equal to "uas"  //  `sudo fstrim -v /`)
- name: Copy udev rule
  ansible.builtin.copy:
    content: "ACTION==\"add|change\", ATTRS{idVendor}==\"{{ usb_enclosure.vendor_id }}\", ATTRS{idProduct}==\"{{ usb_enclosure.product_id }}\", SUBSYSTEM==\"scsi_disk\", ATTR{provisioning_mode}=\"unmap\""
    dest: /etc/udev/rules.d/10-trim_umap.rules
    owner: root
    group: root
    mode: 0644
  become: true

- name: Enable systemd fstrim timer
  ansible.builtin.service:
    name: fstrim.timer
    enabled: true
    state: started
  become: true
