---
# Enables TRIM support via UASP    (validate: `lsusb -t` -> check whether "Driver" is equal to "uas"  //  `sudo fstrim -v /`)
- name: Copy udev rule
  ansible.builtin.template:
    src: 10-trim_umap.rules.j2           # TODO: INLINE ONCE SUPPORTED BY MODULE
    dest: /etc/udev/rules.d/10-trim_umap.rules
    owner: root
    group: root
    mode: 0644
  notify: apply udev rules
  become: true

- name: Enable systemd fstrim timer
  ansible.builtin.service:
    name: fstrim.timer
    enabled: true
    state: started
  become: true
