#!/usr/bin/env ansible-playbook
---
- hosts: all
  roles:
    - role: common
      tags:
        - common

# --  "HW specific"  --
- hosts: hw_specific
  roles:
    - role: hw_specific
      tags:
        - hw_specific

# --  "System specific"  --
- hosts: clients_devel, clients_media, clients_workstation
  roles:
    - role: power_user
    - role: client/base
  vars:
    wallpaper: "/System/Library/Desktop Pictures/Solid Colors/Stone.png" # TODO: GNU/Linux wallpaper
    dock_fav_apps:
      - "'org.gnome.Nautilus.desktop'"
      - "'firefox.desktop'"
      - "'brave-browser.desktop'"
      - "'codium.desktop'"
      - "'org.gnome.Terminal.desktop'"
      - "'gnome-system-monitor.desktop'"
  tags: client_base

- hosts: clients_devel
  roles:
    - role: devel_base
    - role: client/devel
      tags:
        - client_devel

- hosts: clients_media, clients_workstation
  roles:
    - role: client/media
      tags:
        - client_media

- hosts: clients_workstation
  roles:
    - role: client/workstation
      tags:
        - client_workstation

- hosts: servers, servers_devel, servers_home
  roles:
    - role: server/base
      tags: server

- hosts: servers_devel
  roles:
    - role: power_user
    - role: devel_base
  tags:
    - dev_server

- hosts: servers_home
  vars:
    docker_container:
      data_basedir: /{{ os_homedir }}/{{ user.name }}/homeserver/data/
      config_basedir: /{{ os_homedir }}/{{ user.name }}/homeserver/config/
  roles:
    - role: server/3rd-party/internet-pi
      tags:
        - inet_monitoring

    - role: server/home_server/containers/
      tags:
        - containers
  tags:
    - home_server
