---
- name: Ensure data dir 1 exists
  ansible.builtin.file:
    path: '{{ docker_container_data_basedir }}/{{ container_name }}/hole'
    state: directory
    mode: 0755
  become: false

- name: Ensure data dir 2 exists
  ansible.builtin.file:
    path: '{{ docker_container_data_basedir }}/{{ container_name }}/dns'
    state: directory
    mode: 0755
  become: false

- name: Create config dir
  ansible.builtin.file:
    path: '{{ docker_container_config_basedir }}/{{ container_name }}'
    state: directory
    mode: 0755
  become: false

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ docker_container_config_basedir }}/{{ container_name }}/docker-compose.yml'
    mode: '0640'
  become: false
  #notify: Restart pi-hole

- name: Ensure container is running
  community.docker.docker_compose:
    project_src: '{{ docker_container_config_basedir }}/{{ container_name }}/'
    build: false
  become: false
