---
- name: Install prerequisites
  become: true
  apt:
    update_cache: yes
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - libacl1-dev
      - libacl1
      - libssl-dev
      - libb2-dev
      - liblz4-dev
      - libzstd-dev
      - build-essential
      - pkg-config
      - python3-pkgconfig
    state: present

- name: Install file backup tools
  pip:
    name: borgbackup
