---
- name: 'Enable other packages  (TODO: ONLY FOR RASPBIAN)'
  replace:
    path: /etc/apt/sources.list
    regexp: '^# deb http://raspbian'
    replace: 'deb http://raspbian'

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes



- name: Install file general purpose tools
  apt:
    name:
      - tree
      - rename
      - fdupes
      - dos2unix
      - rclone
      - lsof
    state: present

- name: Install file archiving tools
  apt:
    name:
      - pigz
      - pbzip2
#      - pxz
      - zip
      - unzip
    state: present

- name: Install backup tools
  apt:
    name:
      - borgbackup
    state: present

- name: Install monitoring tools
  apt:
    name:
      - neofetch
      - htop
      - psmisc
      - iotop
      - sysstat
      - smartmontools
      - hdparm
      - usbutils
    state: present

- name: Install networking tools
  apt:
    name:
      - nmap
      - speedtest-cli
      - net-tools
      - wget
      - curl
    state: present

- name: Install administration tools
  apt:
    name:
      - mosh
    state: present

- name: Install privacy tools
  apt:
    name:
      - ccrypt
      - cryptsetup
      - zerofree
    state: present

- name: Check luks is installed
  package_facts:
    manager: "auto"

- name: Install privacy tool 'luks sparse file helper'
  copy:
    src: "luks-sparse_helper"
    dest: "/usr/local/bin/luks-sparse_helper"
    owner: root
    group: root
    mode: 0755
  when: "'ccrypt' in ansible_facts.packages"

- name: Install shell related tools
  apt:
    name:
      - moreutils
      - procps      # watch command
      - pv
      - uuid
    state: present

- name: Install dev tools
  apt:
    name:
      - neovim
      - git
      - git-lfs
    state: present

#- name: Init git LFS for current user        # NOT  IDEMPOTENT ???
#  command: git lfs install
#  become: false
