---
- name: Enable other packages
  repace:
    path: /etc/apt/sources.list
    regexp: '^# deb-src'
    replace: 'deb-src'

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes



- name: Install file general purpose tools
  apt:
    name:
      - tree
      - rename
      - fdupes
      - dos2unix
    state: present

- name: Install file backup tools
  apt:
    name:
      - rclone
    state: present

- name: Install file archiving tools
  apt:
    name:
      - pigz
      - pbzip2
      - pxz
      - zip
      - unzip
    state: present

- name: Install monitoring tools
  apt:
    name:
      - neofetch
      - htop
      - pstree
      - iotop
      - sysstat
      - smartmontools
      - hdparm
      - usbutils
    state: present


- name: Install login system stats script
  copy:
    src: "10-show_system_info"
    dest: "/etc/profile.d/10-show_system_info"
    owner: "root"
    group: "root"
    mode: 0644


- name: Install networking tools
  apt:
    name:
      - nmap
      - speedtest-cli
      - net-tools
      - wget
    state: present

- name: Install administration tools
  apt:
    name:
      - mosh
      #- unattended-upgrades
    state: present

- name: Install privacy tools
  apt:
    name:
      - ccrypt
      - cryptsetup
      - zerofree
    state: present

- name: Install privacy tool 'luks sparse file helper'
  copy:
    src: "luks-sparse_helper"
    dest: "/usr/local/bin/luks-sparse_helper"
    owner: "root"
    group: "root"
    mode: 0644
  when: "'ccrypt' in ansible_facts.packages"

- name: Install shell related tools
  apt:
    name:
      - moreutils
      - watch
      - pv
      - uuid
    state: present

- name: Install dev tools
  apt:
    name:
      - neovim
      - git
      - git-lfs
    state: present

- name: Init git LFS for current user
  command: git lfs install
  become: false



