---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: '{{ container_name }}'
    image: containrrr/watchtower:armhf-latest
    restart_policy: always

    hostname: '{{ container_name }}'

    user: '{{ user_uid }}:{{ user_gid }}'
    # Required for binding to a privliged port (ports which are lower than 1024)

    networks:
      - '{{ docker_default_network }}'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /home/{{ user_name }}/.docker/config.json:/config.json

    env:
      - TZ:                      '{{ timezone }}'
      - WATCHTOWER_CLEANUP:      true
      # - WATCHTOWER_SCHEDULE: '{{ container_cron_schedule }}'
      # Filter by enable label
      - WATCHTOWER_LABEL_ENABLE: true

      #- WATCHTOWER_NOTIFICATIONS=email
      # - Emailing
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER:          '{{ notifications_mail_server_host }}'
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT:     '{{ notifications_mail_server_port }}'
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER:     '{{ notifications_mail_server_username }}'
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: '{{ notifications_mail_server_password }}'
      #- WATCHTOWER_NOTIFICATION_EMAIL_FROM:            '{{ notifications_mail_server_username }}'
      #- WATCHTOWER_NOTIFICATION_EMAIL_TO:              '{{ system_admin_mail }}'
      #- WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG:      'RPi maintenance -'

    # command: --run-once
    command: --schedule "{{ container_cron_schedule }}"
