---
# !!  IMPORTANT: We cannot simply check for the image and skipt this step since we need the compose file  !!
- name: Clone repo
  become: false
  git:
    repo: https://github.com/therealthingy/rpi-pwm.git
    dest: '{{ docker_container_config_basedir }}/{{ rpi_fan_pwm_container_name }}/'
    clone: yes
    depth: 1
    update: yes
  register: repo_clone
  failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in the destination' in repo_clone.msg

- name: Ensure container is running
  community.docker.docker_compose:
    project_src: '{{ docker_container_config_basedir }}/{{ rpi_fan_pwm_container_name }}/'
    build: true
  become: false
