---
- name: Check whether rpi-pwm image exists already
  docker_image_info:
    name: rpi-pwm
  register: result

- name: Clone repo
  become: false
  git:
    repo: https://github.com/therealthingy/rpi-pwm.git
    dest: '{{ docker_container_config_basedir }}/{{ rpi_fan_pwm_container_name }}/'
    clone: yes
    depth: 1
    update: yes
  when: result.images == ""

- name: Ensure container is running
  community.docker.docker_compose:
    project_src: '{{ docker_container_config_basedir }}/{{ rpi_fan_pwm_container_name }}/'
    build: true
  become: false
