---
- name: Gather host data & set it as facts
  block:
    - name: Gather data
      block:
        - name: '[Debian/Ubuntu]'
          block:
            - name: 'Check if GNOME is used as desktop environment  (TODO: revise)'
              ansible.builtin.command: which gsettings
              failed_when: false
              changed_when: false
              check_mode: false
              when: gathered_workstation_facts is not defined
              register: result_gnome_command
              become: false
          when: ansible_facts.os_family != 'Darwin'

        - name: '[Darwin]'
          block:
            - name: Check whether MacBook
              ansible.builtin.shell: sysctl hw.model | grep -o MacBook
              register: result_mac_model
              failed_when: false
              changed_when: false
              become: false
          when: ansible_facts.os_family == 'Darwin'


    - name: Set variables (as facts)
      block:
      # --  Set workstation facts  --
        - name: '[Debian/Ubuntu]'
          ansible.builtin.set_fact:
            desktop_envs: "{{ ['GNOME' if result_gnome_command.rc == 0] }}"
            firefox_package_name: "{{ 'firefox-esr' if ansible_facts.distribution == 'Debian' else 'firefox' }}"
            gathered_workstation_facts: True
          when: ansible_facts.os_family != 'Darwin'
          become: false

        - name: '[Debian/Ubuntu]'
          ansible.builtin.set_fact:
            workstation_is_a_macbook: "{{ True if result_mac_model.rc == 0 else False }}"
            gathered_workstation_facts: True
          when: ansible_facts.os_family == 'Darwin'
          become: false
  when: gathered_workstation_facts is not defined


#-  ansible.builtin.debug:
#    msg:
#      desktop_envs={{ desktop_envs }}
#      firefox_package_name={{ firefox_package_name }}
