---
- name: Install open-vm-tools
  ansible.builtin.apt:
    name:
      - open-vm-tools
      - fuse
    state: present

- name: Mount vmware shares on boot
  ansible.posix.mount:
    path: '{{ mount_dir }}'
    src: 'vmhgfs-fuse'
    fstype: fuse
    opts: 'defaults,allow_other'
    state: mounted
