---
- name: Install open-vm-tools
  ansible.builtin.apt:
    name:
      - open-vm-tools
      - gvfs-fuse         # NOTE: Package `fuse` causes autoremove of GNOME packages (https://askubuntu.com/questions/1406236/desktop-icons-gone-in-22-04), hence install `gvfs-fuse`
    state: present

- name: Mount vmware shares on boot
  ansible.posix.mount:
    path: '{{ mount_dir }}'
    src: 'vmhgfs-fuse'
    fstype: fuse
    opts: 'defaults,allow_other'
    state: mounted

- name: Create symlink in home dir
  ansible.builtin.file:
    src: /mnt/hgfs/
    dest: '/home/{{ user_name }}/vmware-shares'
    state: link
  become: false
