---
- name: Install media tools
  block:
    - name: '[Darwin / Debian/Ubuntu]'
      ansible.builtin.package:
        name:
          - exiftool
          - ffmpeg
          - gifsicle
          - imagemagick
      become: "{{ 'true' if ansible_facts['os_family'] != \"Darwin\" else 'false' }}"
    - name: '[Debian/Ubuntu]'
      community.general.flatpak:
        name:
          - org.videolan.VLC
          - io.github.celluloid_player.Celluloid
        state: present
      become: true
      when: ansible_facts.os_family != 'Darwin'

- name: Install yt-dlp
  community.general.pipx:
    name: yt-dlp
    state: latest
    install_deps: true
    executable: pipx
  become: false
