---
- name: Install media tools
  ansible.builtin.apt:
    name:
      - celluloid
      - vlc
    state: present
  become: true

- name: Install yt-dl
  ansible.builtin.pip:   # NOTE: sudo installs it for ALL users (otherwise only local user)
    name: yt-dlp
  become: true
