---
- name: restart docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true

- name: restart nftables
  ansible.builtin.service:
    name: nftables
    state: restarted
  become: true

- name: restart networking daemon
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted
  become: true
