---
- name: Install homebrew casks
  block:
    - name: Create dir
      ansible.builtin.file:
        path: "/Applications/{{ homebrew_cask_dir.dir }}"
        state: directory
        owner: "{{ user.name }}"
        group: "{{user.group_name}}"
        mode: 0755
      with_items: "{{ packages_homebrew_casks }}"
      loop_control:
        loop_var: homebrew_cask_dir
      become: false
      when: homebrew_cask.0.dir is defined and homebrew_cask.0.dir

    - name: Install packages # TODO: Use `geerlingguy.mac.homebrew`
      community.general.homebrew_cask:
        name: "{{ homebrew_cask.1 }}"
        state: latest
        install_options: 'appdir=/Applications/{{ homebrew_cask.0.dir if homebrew_cask.0.dir is defined  and homebrew_cask.0.dir else "" }}'
      with_subelements:
        - "{{ packages_homebrew_casks }}"
        - packages
      loop_control:
        loop_var: homebrew_cask
      become: false
  when: ansible_facts.os_family == 'Darwin'
