---
- ansible.builtin.include_tasks: packages.yml



- name: Configure git (II)
  community.general.git_config:
    name: '{{ git_config_var.name }}'
    value: '{{ git_config_var.value }}'
    scope: '{{ git_config_var.scope }}'
  with_items:
    - name: user.name
      value: '{{ git_config.name }}'
      scope: global
    - name: user.email
      value: '{{ git_config.email }}'
      scope: global
  loop_control:
    loop_var: git_config_var
  become: false
  when: git_config is defined
