---
- ansible.builtin.include_tasks: '{{ included_dev_server_task }}'
  loop:
    - packages-sysdev.yml
    - packages-python.yml
#    - packages-java.yml
  loop_control:
    loop_var: included_dev_server_task


- name: Install misc tools
  block:
    - name: '[Darwin / Debian/Ubuntu]'
      ansible.builtin.package:
        name:
          - flashrom
          - graphviz
          - jq
          - httpie                   # Human-friendly HTTP client for the API era
      become: '{{ package_manager_become }}'
#    - name: '[Debian/Ubuntu]'
#      ansible.builtin.apt:
#        name:
#          - sqlite3                   # SQLite CLI
#        state: present
#      when: ansible_facts.os_family != 'Darwin'
#    - name: '[Darwin]'
#      community.general.homebrew:
#        name:
#          - sqlite
#      become: false
#      when: ansible_facts.os_family == 'Darwin'
