---
- name: Python dev
  block:
    - name: Install packages
      community.general.pipx:
        name: '{{ pip_package }}'
        state: latest
        install_deps: true
        executable: pipx
      with_items:
        - ansible
        - pdm            # TODO: Shell Completion 4 pdm  (https://pdm.fming.dev/latest/)
        - jupyterlab
      loop_control:
        loop_var: pip_package
    - name: Inject packages
      community.general.pipx:
        name: '{{ package.name }}'
        state: inject
        inject_packages: '{{ package.packages }}'
        executable: pipx
      with_items:
        - name: 'ansible'
          packages: ['ansible-lint[yamllint]']
        - name: 'jupyterlab'
          packages: ['pip']                                       # Otherwise update fails …
      loop_control:
        loop_var: package
  become: false


# USAGE:
#   - `source ~/.venvs/science/bin/activate`
#   - `deactivate`
#   - ( `python3 -m venv --upgrade ~/.venvs/science` )
- name: Install Python scientific packages
  ansible.builtin.pip:
    name:
      - numpy
      - pandas
      - matplotlib
#      - scipy
    virtualenv: '{{ os_homedir }}/{{ user.name }}/.venvs/science'
    virtualenv_command: python -m venv
  become: false               # NOTE: sudo installs it for ALL users (otherwise only local user)
