---
# SEE: https://unix.stackexchange.com/questions/39370/how-to-reload-udev-rules-without-reboot
- name: apply udev rules
  ansible.builtin.shell: |
    udevadm control --reload-rules  &&  udevadm trigger
  become: true
