---
- name: Create config dir
  ansible.builtin.file:
    path: '{{ docker_container_config_basedir }}/{{ container_name }}'
    state: directory
    mode: 0755
  become: false

- name: Copy postscript
  ansible.builtin.template:
    src: script-torrent_done.j2
    dest: '{{ docker_container_config_basedir }}/{{ container_name }}/script-torrent_done'
    mode: 0755
  become: false

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ docker_container_config_basedir }}/{{ container_name }}/docker-compose.yml'
    mode: 0640
  become: false

# TODO: Create container, but don't start it  (i.e., `--no-start`; NOTE: not supported currently, see: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html)
