---
container_name: pihole

pihole_config_dir: '/home/{{ user_name }}/pihole/'
pihole_data_dir:   '/home/{{ user_name }}/pihole/data'

pihole_docker_tag: 2022.09.2               # See: https://hub.docker.com/r/pihole/pihole/tags


# DNS Server 1: Cloudflare  (https://1.1.1.1/help)
dns_server1_ipv4: 1.1.1.1
dns_server1_ipv6: 2606:4700:4700::1111

# DNS Server 2: Google DNS  (TODO: CHANGE; https://en.wikipedia.org/wiki/Google_Public_DNS)
dns_server2_ipv4: 8.8.8.8
dns_server2_ipv6: 2001:4860:4860::8888
