---
- name: Install systems programming tools/libs
  ansible.builtin.apt:
    name:
      - shellcheck            # Lint bash scripts
      # Compiler / build tools
      - manpages-dev
      - build-essential       # Includes GNU debugger, g++/GNU compiler collection, and some more tools (`make`) and libraries that are required to compile a program
      #- gcc-multilib          # Useful for cross-compiling   (Debian arm64 -- Error: 'Package '' has no installation candidate')
      - pkg-config
      - cmake
      - cmake-curses-gui
      # Debuggers / Tools  (NOTE: binutils, util-linux & gdb are most likely already installed)
      - binutils              # Contains `readelf`, ...
      - valgrind
      - strace
      # 'Performance' analysis
      - linux-base            # Installs `perf`  (NOTE: Is already installed)
      - time                  # NOTE: Usually implemented as shell builting  (hence must be called directly via `/usr/bin/time ...`)
      #- pahole                # Shows & manipulates data structure layout   (Debian arm64 -- Error: The following packages have unmet dependencies: pahole : Depends: libbpf0)
      # Utils
      - numactl               # More powerful alternative to `taskset`  (useful on NUMA systems, incl. AMD CPUs w/ "chiplet" design)
      # Libs
      - libomp-dev
      - libelf-dev
      - libdw-dev
      # Misc.
      - flex                  # Generates lexical analyzers
      - bison                 # Parser generator
    state: present
  become: true
