---
- name: Install systems programming tools/libs
  ansible.builtin.apt:
    name:
      - shellcheck            # Lint bash scripts
      # Compiler / build tools
      - manpages-dev
      - build-essential       # Includes GNU debugger, g++/GNU compiler collection, and some more tools (`make`) and libraries that are required to compile a program
      - gcc-multilib          # Useful for cross-compiling   (Debian arm64 -- Error: 'Package '' has no installation candidate')
      - clang
      - pkg-config
      - cmake
      - cmake-curses-gui
      - autoconf
      # Debuggers / Tools  (NOTE: binutils, util-linux & gdb are most likely already installed)
      - binutils              # Contains `readelf`, `gprof`, ...
      - strace
      - bpftrace
      - ltrace
      - valgrind
      - kcachegrind           # KDE GUI 2 visualize profiling data (mainly used as visualization frontend for data measured by Cachegrind/Callgrind tools from the Valgrind package)
      - graphviz              # TODO: Apparently required by kcachegrind  ??
      # 'Performance' analysis
      - linux-tools-common    # `perf`  (Performance analysis tools for Linux)
      - linux-tools-generic   # Kernel modules required 4 `perf`
      - hotspot               # UI (similar 2 KCachegrind 4 valgrind, BUT) around perf
      - time                  # NOTE: Usually implemented as shell builting  (hence must be called directly via `/usr/bin/time ...`)
      - pahole                # Shows & manipulates data structure layout
      # Utils
      - numactl               # More powerful alternative to `taskset`  (useful on NUMA systems, incl. AMD CPUs w/ "chiplet" design;  `numastat`)
      # Libs
      - libomp-dev
      - libelf-dev
      - libdw-dev
      # Misc.
      - flex                  # Generates lexical analyzers
      - bison                 # Parser generator
    state: present
  become: true



# Installation steps: https://www.intel.com/content/www/us/en/develop/documentation/vtune-install-guide/top/linux/package-managers.html
#- name: Install VTune
#  block:
#    - name: Add apt Repo
#      # NOTE: Equivalent command: `sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"`
#      ansible.builtin.apt_repository:
#        repo: deb https://apt.repos.intel.com/oneapi all main
#        state: present
#        filename: intel
#        update_cache: yes
#    - name: Install VTune
#      ansible.builtin.apt:
#        name: intel-oneapi-vtune
#  when: ansible_architecture == "x86_64"
#  become: true
