---
- name: Install systems programming tools/libs
  ansible.builtin.apt:
    name:
      # Compiler / build tools
      - build-essential
      - manpages-dev
      - cmake
      - cmake-curses-gui
      # Debuggers / Tools  (binutils, util-linux & gdb are most likely already installed)
      - binutils
      - gdb
      - valgrind
      # Libs
      - libomp-dev
    state: present
  become: true
