---
- name: Install systems programming tools/libs
  ansible.builtin.apt:
    name:
      # Compiler / build tools
      - build-essential
      - manpages-dev
      - cmake
      - cmake-curses-gui
      # Debuggers / Tools  (NOTE: binutils, util-linux & gdb are most likely already installed)
      - binutils
      - gdb
      - valgrind
      # Libs
      - libomp-dev
      # Misc.
      - numactl               # More powerful alternative to `taskset`  (useful on NUMA systems, incl. AMD CPUs w/ "chiplet" design)
    state: present
  become: true
