---
- name: Install
  block:
    - name: Add apt repo and update cache
      ansible.builtin.apt_repository:
        repo: ppa:maveonair/helix-editor
        state: present
        update_cache: true
      when: ansible_facts.distribution == 'Ubuntu'
      become: true
    - name: Install it
      ansible.builtin.package:
        name: helix
      become: '{{ package_manager_become }}'

# TODO: UBUNTU
- name: '[Darwin] Install LSPs'
  community.general.homebrew:
    name:
      - texlab
      - ansible-language-server
      - yaml-language-server
      - taplo
      - bash-language-server
      - sql-language-server
      - lua-language-server
  become: false
  when: ansible_facts.os_family == 'Darwin'

# TODO: https://schembri.me/post/neovim-everywhere-on-macos/
- name: "[Darwin] Post Install -- Finder integration"
  block:
    - name: Install app
      block:
        - ansible.builtin.file:
            path: '/Applications/Development/Editors'
            state: directory
            owner: '{{ user.name }}'
            group: '{{user.group_name}}'
            mode: 0755
        - ansible.builtin.unarchive:
            src: 'apps/Helix-iTerm.app.tar.gz'
            dest: '/Applications/Development/Editors/'
            creates: Helix-iTerm.app
      become: false
      when: ansible_facts.os_family == 'Darwin'
  become: false
  when: ansible_facts.os_family == 'Darwin'


- name: Config
  ansible.builtin.git:
    repo: https://github.com/therealthingy/dothelix.git #git@github.com:therealthingy/dothelix.git
    dest: '{{ os_homedir }}/{{ user.name }}/.config/helix/'
    clone: true
    depth: 1
    update: true
  register: repo_clone
  failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in the destination' in repo_clone.msg
  become: false
