---
- name: 'Config (changes will take effect after logging in again)'
  community.general.osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
    state: present
  with_items:
    - domain: 'com.apple.Dock'        # Apps hidden in Dock;          TODO: `killall Dock`
      key: 'showhidden'
      value: 'true'
      type: 'boolean'
    - domain: 'com.apple.dock'        # Eliminate Dock reveal delay
      key: 'autohide-time-modifier'
      value: '0'
      type: 'int'
  become: false
