---
- name: Scripts
  block:
    - name: Create dir
      block:
        - name: Create dir
          ansible.builtin.file:
            path: '/Users/{{ user.name }}/bin'
            state: directory
            owner: '{{ user.name }}'
            group: '{{ user.group_name }}'
            mode: 0755
        - name: Hide dir
          ansible.builtin.shell: chflags hidden '/Users/{{ user.name }}/bin'
          changed_when: false       # !!!!!!!!!!!!!!!!                            TODO: REVISE
    - name: Copy scripts
      ansible.builtin.template:
        src: '{{ config_file.src }}.j2'
        dest: '{{ config_file.dest_file }}'
        owner: '{{ config_file.owner }}'
        group: '{{ config_file.group }}'
        mode: 0755
      with_items:
        - src: 'bin/home/git-update_repos'
          dest_file: '/Users/{{ user.name }}/bin/git-update_repos'
          owner: '{{ user.name }}'
          group: '{{ user.group_name }}'
      loop_control:
        loop_var: config_file
      become: false


# Must be enabled via: System Settings -> Privacy & Security -> Extensions -> Finder
- name: Finder services
  ansible.builtin.copy:
    src: 'finder-workflows/{{ workflow_file }}/'
    dest: '/Users/{{user.name}}/Library/Services/{{ workflow_file }}'
    owner: '{{ user.name }}'
    group: '{{ user.group_name }}'
    mode: 0755
  with_items:
    - 'Clean LaTeX Junk.workflow'
    - 'Combine PDFs.workflow'
    - 'Convert PDFs to images.workflow'
    - 'MP4 to MP3.workflow'
    - 'Video to GIF.workflow'
  loop_control:
    loop_var: workflow_file
  become: false
