---
- name: Install Docker (Raspbian)
  when: ansible_facts['distribution'] == 'Debian'
  block:
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/raspbian/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: "deb [arch=arm64] https://download.docker.com/linux/raspbian bullseye stable"
      state: present

#  - name: Switch to iptables-legacy
#    alternatives:
#      name: iptables
#      path: /usr/sbin/iptables-legacy

#  - name: Switch to ip6tables-legacy
#    alternatives:
#      name: ip6tables
#      path: /usr/sbin/ip6tables-legacy



- name: Update apt and install docker-ce
  when: ansible_facts['os_family'] == 'Debian'
  apt:
    update_cache: yes
    name: "{{ docker_packages }}"
    state: present

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Add user "{{ username }}" to group docker
  user:
    name: '{{ username }}'
    groups:
      - docker
    append: yes


- name: Install Docker Module for Python
  pip:
    name: docker


- name: Make sure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
