---
- name: Setup mac
  hosts: macs
  become: true

#  handlers:
#    - name: Include handlers.
#      ansible.builtin.import_tasks: tasks/handlers.yml

  pre_tasks:
    - name: Gather facts
      ansible.builtin.import_tasks: tasks/gather_facts.yml

  roles:
    # Equivalent 2 `xcode-select --install`
    - role: elliotweiser.osx-command-line-tools

  tasks:
    - name: Config
      ansible.builtin.import_tasks: tasks/config.yml

    - name: Install packages
      ansible.builtin.import_tasks: tasks/packages.yml

    - name: Install scripts/extensions
      ansible.builtin.import_tasks: tasks/scripts.yml
