---
- name: GNOME wallpaper - Ensure wallpaper dir exists
  ansible.builtin.file:
    path: '/home/{{ user_name }}/Pictures/wallpapers'
    state: directory
  become: false
  when: "'GNOME' in desktop_envs"

- name: GNOME wallpaper - Copy wallpaper file
  ansible.builtin.copy:
    src: Ballmer.jpg
    dest: '/home/{{ user_name }}/Pictures/wallpapers/Ballmer.jpg'
  become: false
  when: "'GNOME' in desktop_envs"

- name: GNOME wallpaper - Set it
  community.general.dconf:
    key: '/org/gnome/desktop/background/picture-uri'
    value: "'file:///home/{{ user_name }}/Pictures/wallpapers/Ballmer.jpg'"
  become: false
  when: "'GNOME' in desktop_envs"
