---
- name: Change GNOME wallpaper
  block:
    - name: Ensure wallpaper dir exists
      ansible.builtin.file:
        path: '/home/{{ user_name }}/Pictures/wallpapers'
        state: directory

    - name: Copy wallpapers
      ansible.posix.synchronize:
        src: wallpapers/
        dest: '/home/{{ user_name }}/Pictures/wallpapers/'

    - name: Change wallpaper
      community.general.dconf:
        key: '/org/gnome/desktop/background/picture-uri'
        value: "'file:///home/{{ user_name }}/Pictures/wallpapers/{{ gnome_wallpaper }}'"
  become: false
  when: "'GNOME' in desktop_envs"



- name: Copy references to Desktop
  ansible.posix.synchronize:
    src: references/
    dest: '/home/{{ user_name }}/Desktop/'
  become: false
