---
- name: Copy wallpaper file
  ansible.builtin.copy:
    src: Ballmer.jpg
    dest: '/home/{{ user_name }}/.wallpaper.jpg'
  become: false
  when: "'GNOME' in desktop_envs"

- name: Set GNOME Wallpaper
  community.general.dconf:
    key: '/org/gnome/desktop/background/picture-uri'
    value: "'file:///home/{{ user_name }}/.wallpaper.jpg'"
  become: false
  when: "'GNOME' in desktop_envs"
