---
#- name: Change GNOME wallpaper
#  block:
#    - name: Ensure wallpaper dir exists
#      ansible.builtin.file:
#        path: '/home/{{ user.name }}/Pictures/wallpapers'
#        state: directory
#
#    - name: Copy wallpapers
#      ansible.posix.synchronize:
#        src: wallpapers/
#        dest: '/home/{{ user.name }}/Pictures/wallpapers/'
#
#    - name: Update GNOME setting
#      community.general.dconf:
#        key: '/org/gnome/desktop/background/picture-uri'
#        value: "'file:///home/{{ user.name }}/Pictures/wallpapers/{{ gnome_wallpaper }}'"
#  when: "'GNOME' in desktop_envs"
#  become: false



- name: Copy dev references to Desktop
  ansible.posix.synchronize:
    src: references/
    dest: '/home/{{ user.name }}/Desktop/'
  become: false
