---
- name: Configure
  block:
    - name: Set config as vars
      ansible.builtin.set_fact:
        firefox_profiles:
          default:
            extensions:
              # URL on addons.mozilla.org
              - foxyproxy-standard

    - name: "Run 'staticdev.firefox' role"
      ansible.builtin.include_role:
        name: staticdev.firefox
  become: false
