---
- name: 'Check if grub is used  (TODO: revise)'
  ansible.builtin.command: which update-grub
  become: false
  failed_when: false
  changed_when: false
  check_mode: false
  register: result_grub_command

- name: Enable grub verbose boot
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=\".*\"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
    state: present
  become: true
  when: result_grub_command.rc == 0
  register: result_grub_config_updated

- name: grub makeconfig
  become: true
  ansible.builtin.shell: update-grub
  when: result_grub_config_updated.changed
