---
- name: Install networking tools
  ansible.builtin.apt:
    name:
      - wireshark
      - openvpn
    state: present

- name: Install db tools
  ansible.builtin.apt:
    name:
      - sqlitebrowser
#      TODO (No package matching 'mysql-workbench' is available)
#      - mysql-workbench-community
    state: present

- include_tasks: ../../../server/dev_server/tasks/packages.yml

# KEEP IN MIND: Logout is required for app to show up
- name: Install IntelliJ IDEs
  community.general.flatpak:
    name:
      - com.jetbrains.CLion
      - com.jetbrains.PyCharm-Professional
    state: present


#- name: Install LaTex
#  ansible.builtin.apt:
#    name:
#      - texlive-full
#      - texmaker
#    state: present
