---
- include_tasks: ../../../server/dev_server/tasks/packages.yml

- name: Install networking tools
  ansible.builtin.apt:
    name:
      - wireshark
      - openvpn
    state: present

- name: Install db tools
  community.general.flatpak:
    name:
      - org.sqlitebrowser.sqlitebrowser
      - io.dbeaver.DBeaverCommunity
    state: present

- name: Install misc tools
  community.general.flatpak:
    name:
      - com.github.artemanufrij.graphui
      - com.github.artemanufrij.regextester
      - org.ghidra_sre.Ghidra
      - com.syntevo.SmartGit
    state: present


# KEEP IN MIND: Logout is required for app to show up
- name: Install IntelliJ IDEs
  community.general.flatpak:
    name:
      - com.jetbrains.CLion
      - com.jetbrains.PyCharm-Professional
    state: present


#- name: Install LaTex
#  ansible.builtin.apt:
#    name:
#      - texlive-full
#      - texmaker
#    state: present
