---
- ansible.builtin.include_tasks: ../../../server/dev_server/tasks/packages.yml

- name: Install networking tools
  ansible.builtin.apt:
    name:
      - wireshark
      - openvpn
    state: present
  become: true
  when: ansible_facts['os_family'] != "Darwin"

#- name: Install db tools
#  community.general.flatpak:
#    name:
#      - org.sqlitebrowser.sqlitebrowser
#      - io.dbeaver.DBeaverCommunity
#    state: present
#  become: true
#  when: ansible_facts['os_family'] != "Darwin"

- name: Install misc tools
  block:
    - name: '[Debian/Ubuntu]'
      block:
        - community.general.flatpak:
            name:
              - com.github.tchx84.Flatseal             # Helps managing Flatpak permissions & file storage
              - org.ghidra_sre.Ghidra
#              - com.github.artemanufrij.graphui        # Graph visualization based on graphviz with included a text editor and a preview area
#              - com.github.artemanufrij.regextester
#              - com.syntevo.SmartGit
#              - com.getpostman.Postman
            state: present
#        - ansible.builtin.apt:
#          name:
#            - timeshift
#          state: present
      become: true
      when: ansible_facts['os_family'] != "Darwin"
    - name: '[Darwin / Debian/Ubuntu]'
      ansible.builtin.package:
        name:
          - flashrom
          - graphviz
          - jq
      become: "{{ 'true' if ansible_facts['os_family'] != \"Darwin\" else 'false' }}"


- name: Install shared packages
  ansible.builtin.import_tasks: ./package-latex.yml
