---
- name: Install networking tools
  ansible.builtin.apt:
    name:
      - wireshark
      - openvpn
    state: present

- include_tasks: ../../../server/dev_server/tasks/packages.yml

- name: Install IDEs
  community.general.snap:
    name:
      - clion
      - pycharm-professional
    state: present
    classic: true
  when: ansible_facts.distribution == 'Ubuntu'
