---
- name: Install networking tools
  ansible.builtin.apt:
    name:
      - wireshark
      - openvpn
      - netcat
    state: present

- include_tasks: ../../../server/dev_server/tasks/packages.yml

# TODO: GET RID OF SNAP VERSION
- name: Install IDEs
  community.general.snap:
    name:
      - clion
      - pycharm-professional
    state: present
    classic: true
  when: ansible_facts.distribution == 'Ubuntu'

- name: Install LaTex
  ansible.builtin.apt:
    name:
      - texlive-full
      - texmaker
    state: present
