---
- ansible.builtin.include_tasks: ../../../server/dev_server/tasks/packages.yml

- name: Install networking tools
  ansible.builtin.apt:
    name:
      - wireshark
      - openvpn
    state: present
  become: true

#- name: Install db tools
#  community.general.flatpak:
#    name:
#      - org.sqlitebrowser.sqlitebrowser
#      - io.dbeaver.DBeaverCommunity
#    state: present
#  become: true

- name: Install misc tools
  block:
    - community.general.flatpak:
        name:
          - com.github.tchx84.Flatseal             # Helps managing Flatpak permissions & file storage
          - org.ghidra_sre.Ghidra
          #- com.github.artemanufrij.graphui        # Graph visualization based on graphviz with included a text editor and a preview area
          #- com.github.artemanufrij.regextester
          - com.syntevo.SmartGit
          - com.getpostman.Postman
        state: present
    - ansible.builtin.apt:
        name:
          - graphviz
        state: present
  become: true


## KEEP IN MIND: Logout is required for app to show up
#- name: Install IntelliJ IDEs
#  community.general.flatpak:
#    name:
#      - com.jetbrains.CLion
#      - com.jetbrains.PyCharm-Professional
#    state: present
#  become: true


#- name: Install LaTex
#  ansible.builtin.apt:
#    name:
#      - texlive-full
#      - texmaker
#    state: present
#  become: true
