---
- name: Create config dir
  ansible.builtin.file:
    path: '{{ docker_container_config_basedir }}/{{ container_name }}'
    state: directory
    mode: 0755
  become: false

- name: Copy config files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0640
  become: false
  with_items:
    - { src: 'docker-compose.yml.j2', dest: '{{ docker_container_config_basedir }}/{{ container_name }}/docker-compose.yml' }
    - { src: 'stglobalignore.j2', dest: '{{ syncthing_storage_path }}/.stglobalignore' }

- name: Ensure container is running
  community.docker.docker_compose:
    project_src: '{{ docker_container_config_basedir }}/{{ container_name }}/'
    build: false
  become: false
