---
- name: Install nala
  block:
    - name: nala - Add apt signing key
      # NOTE: Equivalent command: `wget -O - https://deb.volian.org/volian/scar.key | sudo apt-key add -`; Show keys: `apt-key list`
      ansible.builtin.apt_key:
        url: https://deb.volian.org/volian/scar.key
        keyring: /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg
        state: present

    - name: nala - Add apt repo and update cache
      # NOTE: Equivalent command: `sudo add-apt-repository 'deb [arch={{ cpu_arch }}] http://deb.volian.org/volian/ scar main'`
      ansible.builtin.apt_repository:
        repo: deb [arch={{ cpu_arch }}] http://deb.volian.org/volian/ scar main
        filename: volian-archive-scar-unstable
        state: present
        update_cache: true

    # CHECK via: `apt-cache policy`  ('Pin-Priority': https://wiki.ubuntuusers.de/Apt-Pinning/#Werte-fuer-Pin-Priority)
    - name: nala - Pin apt repo
      ansible.builtin.template:
        src: linux/apt-pin.pref.j2
        dest: /etc/apt/preferences.d/nala.pref
        owner: root
        group: root
        mode: 0644
      vars:
        apt_pin_packages:
          - target: 'origin deb.volian.org'


    # -------- TODO: TEMPORARY WORKARDOUND FOR RPI --------
    - name: nala - Set package name
      ansible.builtin.set_fact:
        nala_package_name: "{{ 'nala' if ansible_architecture == 'x86_64' else 'nala-legacy' }}"
    # -----------------------------------------------------


    - name: nala - Install it
      ansible.builtin.apt:
        name: '{{ nala_package_name }}'
        state: present
  when: ansible_os_family == 'Debian'
  become: true
