---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: '{{ container_name }}'
    # $$$ Todo: Tag aarch64 $$$
    image: vaultwarden/server:latest
    restart_policy: always

    user: '{{ user_uid }}:{{ user_gid }}'
    # Required for binding to a privliged port (ports which are lower than 1024)
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0

    networks:
      - '{{ docker_default_network }}'

    volumes:
      - '{{ container_dir_data }}/:/data/'

    env:
      - TZ:                '{{ timezone }}'
      - DATA_FOLDER:       /data
      - DATABASE_URL:      /data/db.sqlite3
      - WEBSOCKET_ENABLED: true
      - SIGNUPS_ALLOWED:   true
      - SIGNUPS_VERIFY:    false
      - DOMAIN:            'https://{{ container_url }}'

      # --- Emailing
      # - SMTP_HOST:           '{{ notifications_mail_server_host }}'
      # - SMTP_FROM:           '{{ notifications_mail_server_username }}'
      # - SMTP_FROM_NAME:      'Bitwarden_RS'
      # - SMTP_PORT:           '{{ notifications_mail_server_port }}'
      # - SMTP_SECURITY:       starttls
      # - SMTP_USERNAME:       '{{ notifications_mail_server_username }}'
      # - SMTP_PASSWORD:       '{{ notifications_mail_server_password }}'
      # - SMTP_AUTH_MECHANISM: "Plain"
      # - SMTP_TIMEOUT:        15

    # REFERENCE: https://docs.traefik.io/configuration/backends/docker/#on-containers
    labels:
      - com.centurylinklabs.watchtower.enable:                              true
      - docker-volume-backup.stop-during-backup:                            true
      - traefik.enable:                                                     true
      - traefik.docker.network:                                             '{{ docker_default_network }}'
      - traefik.http.routers.bitwarden-ui-http.rule:                        Host(`{{ container_url }}`)
      - traefik.http.routers.bitwarden-ui-http.service:                     bitwarden-ui
      - traefik.http.services.bitwarden-ui.loadbalancer.server.port:        80
      - traefik.http.routers.bitwarden-websocket-http.rule:                 Host(`{{ container_url }}`) && Path(`/notifications/hub`)
      - traefik.http.routers.bitwarden-websocket-http.service:              bitwarden-websocket
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port: 3012
