---
- include_tasks: '{{ included_common_config_task }}'
  loop:
    - config-grub_verbose_boot.yml
    - config-ssh.yml
  loop_control:
    loop_var: included_common_config_task


- name: Enable passwordless sudo for {{ user_name }}
  ansible.builtin.copy:
    content: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
    dest: '/etc/sudoers.d/010_{{ user_name }}-nopasswd'
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s
