---
- name: 'Check if grub is used  (TODO: revise)'
  # NOTE: `PATH` may not be set correctly (e.g., on Debian)
  ansible.builtin.command: which /sbin/update-grub
  become: false
  failed_when: false
  changed_when: false
  check_mode: false
  register: result_grub_command


- name: Change grub settings
  block:
    - name: Change config file to enable verbose boot
      ansible.builtin.lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=\".*\"$'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
        state: present
      register: result_grub_verbose_updated

    - name: Change config file and set no boot timeout
      ansible.builtin.lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_TIMEOUT=[0-9]+$'
        line: 'GRUB_TIMEOUT=0'
        state: present
      become: true
      register: result_grub_timeout_updated

    - name: grub makeconfig
      ansible.builtin.shell: update-grub
      when: result_grub_verbose_updated.changed or result_grub_timeout_updated.changed
  become: true
  when: result_grub_command.rc == 0
