---
# Config (refer to https://wiki.archlinux.org/title/locale):
#   - Files:
#     - `/etc/locale.gen`: Locales to generate
#     - `/etc/default/locale`: Set by update-locale
#     - ~~`/etc/environment`~~
#   - Commands:
#     - `locale -a`: Display a list of all available locales
#     - `sudo locale-gen "en_US.UTF-8"`: Generate locale
- name: locale-gen
  block:
    # NOTE: Equivalent command: `sudo locale-gen en_US.UTF-8`
    - name: Generate locale {{ locale }}
      community.general.locale_gen:
        name: '{{ locale }}'
        state: present
      become: true

    - name: "Fix ssh locale issue  (causing '<command>: Cannot set LC_CTYPE to default locale: No such file or directory')"
      ansible.builtin.lineinfile:
        dest: /etc/default/locale
        regexp: '{{ common_locale_fix_item.regex }}'
        line: '{{ common_locale_fix_item.line }}'
        state: present
      with_items:
        - { regex: '^LANG="?{{ locale }}"?$', line: 'LANG={{ locale }}' }
        - { regex: '^LC_ALL="?{{ locale }}"?$', line: 'LC_ALL={{ locale }}' }
      loop_control:
        loop_var: common_locale_fix_item
      become: true


# Check result: `sudo dpkg-reconfigure tzdata`
- name: "Set timezone to '{{ timezone }}'"
  community.general.timezone:
    name: '{{ timezone }}'
  become: true


- name: Set hostname
  block:
    - name: Get current hostname
      ansible.builtin.shell: hostname            # ALTERNATIVE for hostname: ansible_hostname
      register: result_hostname
      changed_when: false

    - name: "Set hostname to '{{ hostname }}'"
      ansible.builtin.hostname:
        name: '{{ hostname }}'
      become: true

    # IMPORTANT: Requires this special indentation, otherwise other entries will be replaced !!
    - name: Fix hosts file
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1\s+{{ result_hostname.stdout }}$'
        line: '127.0.0.1	{{ hostname }}'
        state: present
      become: true
  when: hostname is defined


- ansible.builtin.include_tasks: '{{ included_common_config_task }}'
  loop:
    - config-grub.yml
    - config-ssh.yml
  loop_control:
    loop_var: included_common_config_task


- name: "Enable password-less sudo for '{{ user_name }}'"
  ansible.builtin.copy:
    content: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
    dest: '/etc/sudoers.d/010_{{ user_name }}-nopasswd'
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s
  become: true
  when: passwordless_sudo_enabled is defined and passwordless_sudo_enabled
