---
# TODO: for all systems: common ansible ssh-key
#- name: Add ssh key for {{ user_name }}
#  authorized_key:
#    user: {{ user_name }}
#    key: {{ user_ssh_key }}


- name: Change SSH settings
  block:
    - name: Disable root login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        validate: '/usr/sbin/sshd -T -f %s'

    - name: Enable public key authentication
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
        validate: '/usr/sbin/sshd -T -f %s'

    - name: Disable password login
      block:
        - name: Update conf file
          ansible.builtin.lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '{{ common_ssh_item.regex }}'
            line: '{{ common_ssh_item.line }}'
            validate: '/usr/sbin/sshd -T -f %s'
          loop_control:
            loop_var: common_ssh_item
          with_items:
            - { regex: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
            - { regex: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
        - name: Rmv contradicting conf file (Ubuntu Server)
          ansible.builtin.file:
            path: /etc/ssh/sshd_config.d/50-cloud-init.conf
            state: absent
          when: ansible_facts.distribution == 'Ubuntu'

    - name: Change ssh port
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: 'Port {{ ssh_port }}'
        validate: '/usr/sbin/sshd -T -f %s'
      when: ssh_port is defined


    - name: Allow client to pass locale environment variables
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#?AcceptEnv LANG LC_\*$'
        line: 'AcceptEnv LANG LC_*'
        validate: '/usr/sbin/sshd -T -f %s'
  notify: restart ssh daemon
  become: true
