---
- name: Set hostname
  block:
    - name: Get current hostname
      ansible.builtin.shell: hostname            # ALTERNATIVE for hostname: ansible_hostname
      register: result_hostname
      changed_when: false

    - name: Set new hostname
      ansible.builtin.hostname:
        name: '{{ domainname }}'
      become: true

    # IMPORTANT: Requires this special indentation, otherwise other entries will be replaced !!
    - name: Fix hosts file
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1\s+{{ result_hostname.stdout }}$'
        line: '127.0.0.1	{{ hostname }}'
        state: present
      become: true
  when: hostname is defined


- include_tasks: '{{ included_common_config_task }}'
  loop:
    - config-grub_verbose_boot.yml
    - config-ssh.yml
  loop_control:
    loop_var: included_common_config_task


- name: Enable passwordless sudo for {{ user_name }}
  ansible.builtin.copy:
    content: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
    dest: '/etc/sudoers.d/010_{{ user_name }}-nopasswd'
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s
