---
- name: Generate the locale
  become: true
  community.general.locale_gen:
    name: "{{ locale }}"
    state: present

- include_tasks: user_config.yml

- include_tasks: ssh.yml

- include_tasks: packages.yml
