---
- name: Generate the locale
  become: true
  community.general.locale_gen:
    name: '{{ locale }}'
    state: present

- include_tasks: '{{ item }}'
  loop:
    - config-user.yml
    - config-ssh.yml
    - packages.yml
