---
- name: Generate the locale
  become: true
  community.general.locale_gen:
    name: '{{ locale }}'
    state: present

- include_tasks: config-user.yml

- include_tasks: config-ssh.yml

- include_tasks: packages.yml
