---
- name: Generate the locale
  become: true
  community.general.locale_gen:
    name: '{{ locale }}'
    state: present


- include_tasks: '{{ included_task }}'
  loop:
    - config-user.yml
    - config-ssh.yml
    - packages.yml
  loop_control:
    loop_var: included_task
