---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist
    clean: true
    autoremove: true
    allow_downgrade: true


- name: Install file general purpose tools
  ansible.builtin.apt:
    name:
      - file
      - tree
      - rename
      - fdupes
      - dos2unix
      - rsync
      - rclone              # Cloud storage management software
      - lsof
      - neovim
    state: present

- name: Install file archiving tools
  ansible.builtin.apt:
    name:
      - pigz
      - pbzip2
      - zip
      - unzip
    state: present

- name: Install backup tools
  ansible.builtin.apt:
    name:
      - borgbackup
    state: present

- name: Install monitoring tools
  ansible.builtin.apt:
    name:
      - neofetch
      - atop
      - htop
      - psmisc
      - iotop
      - sysstat
      - smartmontools
      - hdparm
      - usbutils
    state: present

- name: Install networking tools
  ansible.builtin.apt:
    name:
      - nmap
      - netcat
      - tcpdump
      - iproute2       # NOTE: net-tools is deprecated
      - wget
      - curl
      - iperf
      - speedtest-cli
    state: present

- name: Install administration tools
  ansible.builtin.apt:
    name:
      # Most likely already installed (contains MANY utilities)
      - util-linux
      # - abstraction of the used apt repositories (allows easily managing distribution & independent software vendor software sources)  -> `add-apt-repository`, `apt-add-repository`
      - software-properties-common
      - ssh
      - mosh
    state: present

- name: Privacy tools
  block:
    - name: Install privacy tools
      ansible.builtin.apt:
        name:
          - ccrypt
          - cryptsetup
          - zerofree
        state: present

    - name: Install luks sparse file helper
      ansible.builtin.copy:
        src: bin/luks-sparse_helper
        dest: /usr/local/bin/luks-sparse_helper
        owner: root
        group: root
        mode: 0755


- name: Install shell related tools
  ansible.builtin.apt:
    name:
      - moreutils
      - procps      # watch command
      - pv
      - uuid
    state: present


# (!!  ALSO REQUIRED FOR ZSH  !!)
- name: Install git
  ansible.builtin.apt:
    name:
      - git
      - git-lfs
    state: present

#- name: Init git LFS for current user        # TODO: NOT  IDEMPOTENT ???
#  ansible.builtin.command: git lfs install
#  become: false


- include_tasks: '{{ item }}'
  loop:
    - package-python.yml
    - package-tmux.yml
    - package-zsh.yml
    - package-nala.yml
