---
- name: Install Python and pip
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3
      - python3-pip
    state: present


- name: Switch to python3
  community.general.alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name: Switch to pip3
  community.general.alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3

# NOTE: 2 check for updates, use: `pip-review --local --auto`
- name: Install pip packages
  ansible.builtin.pip:
    name:
      - pip-review


- name: Install pip packages required by Ansible modules
  ansible.builtin.pip:
    name:
      - python-apt
      - psutil          # Required for dconf module
