---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist
    autoremove: true


- name: Install file general purpose tools
  ansible.builtin.apt:
    name:
      - tree
      - rename
      - fdupes
      - dos2unix
      - rclone
      - lsof
      - neovim
    state: present

- name: Install file archiving tools
  ansible.builtin.apt:
    name:
      - pigz
      - pbzip2
#      - pxz
      - zip
      - unzip
    state: present

- name: Install backup tools
  ansible.builtin.apt:
    name:
      - borgbackup
    state: present

- name: Install monitoring tools
  ansible.builtin.apt:
    name:
      - neofetch
      - htop
      - psmisc
      - iotop
      - sysstat
      - smartmontools
      - hdparm
      - usbutils
    state: present

- name: Install networking tools
  ansible.builtin.apt:
    name:
      - nmap
      - speedtest-cli
      - iperf
      - net-tools
      - wget
      - curl
    state: present

- name: Install administration tools
  ansible.builtin.apt:
    name:
      - ssh
      - mosh
    state: present

- name: Install privacy tools
  ansible.builtin.apt:
    name:
      - ccrypt
      - cryptsetup
      - zerofree
    state: present

- name: Check whether luks is installed
  ansible.builtin.package_facts:
    manager: 'auto'

- name: Install privacy tool 'luks sparse file helper'
  ansible.builtin.copy:
    src: bin/luks-sparse_helper
    dest: /usr/local/bin/luks-sparse_helper
    owner: root
    group: root
    mode: 0755
  when: "'ccrypt' in ansible_facts.packages"

- name: Install shell related tools
  ansible.builtin.apt:
    name:
      - moreutils
      - procps      # watch command
      - pv
      - uuid
    state: present


- include_tasks: package-python.yml

- include_tasks: package-tmux.yml

# (!!  ALSO REQUIRED FOR ZSH  !!)
- name: Install git
  ansible.builtin.apt:
    name:
      - git
      - git-lfs
    state: present

#- name: Init git LFS for current user        # TODO: NOT  IDEMPOTENT ???
#  ansible.builtin.command: git lfs install
#  become: false

- include_tasks: package-zsh.yml
