---
- name: Install zsh
  apt:
    name:
      - zsh
    state: present

- name: Create zsh config dir
  become: false
  file:
    path: '/home/{{ user_name }}/.config/zsh/'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0755

- name: Install oh-my-zsh
  become: false
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: '/home/{{ user_name }}/.oh-my-zsh/'
    clone: true
    depth: 1
    update: true

- name: Install oh-my-zsh plugins
  become: false
  git:
    repo: 'https://github.com/zsh-users/{{ item }}'
    dest: '/home/{{ user_name }}/.oh-my-zsh/custom/plugins/{{ item }}/'
    clone: true
    depth: 1
    update: true
  with_items:
    - 'zsh-syntax-highlighting'
    - 'zsh-autosuggestions'

- name: Install oh-my-zsh theme
  become: false
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: '/home/{{ user_name }}/.oh-my-zsh/custom/themes/powerlevel10k/'
    clone: true
    depth: 1
    update: true

- name: Copy zsh config files
  become: false
  copy:
    src: '{{ item.src }}'
    dest: '/home/{{ user_name }}/.config/zsh/{{ item.dest_file }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
  with_items:
    - { src: 'zshenv', dest_file: '.zshenv' }
    - { src: 'zshfunc', dest_file: '.zshfunc' }
    - { src: 'zsh_theme_p10k', dest_file: '.p10k.zsh' }
    - { src: 'zshrc', dest_file: '.zshrc' }

- name: Set zsh config dir
  become: false
  file:
    src: '/home/{{ user_name }}/.config/zsh/.zshenv'
    dest: '/home/{{ user_name }}/.zshenv'
    state: link

- name: Change shell
  user:
    name: '{{ user_name }}'
    shell: /bin/zsh
