---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist
    clean: true
    autoremove: true
    allow_downgrade: true
  become: true


- name: Install file general purpose tools
  ansible.builtin.apt:
    name:
      - libc-bin                      # Collection of helper programs, so called binary tools, that work in conjunction with libc  (`iconv`, ..)
      - file
      - tree
      - rename
      - detox                         # Renames files to make them easier to work w/ under Unix & related OSes
      - fdupes
      - dos2unix
      - rsync
      - rclone                        # Cloud storage management software
      - lsof
      - neovim
    state: present
  become: true

- name: Set alternatives for nvim
  community.general.alternatives:
    name: '{{ common_nvim_alt.name }}'
    link: '{{ common_nvim_alt.link }}'
    path: '{{ common_nvim_alt.path }}'
  with_items:
    - { name: editor, link: /usr/bin/editor, path: /usr/bin/nvim }
    - { name: vi,     link: /usr/bin/vi,     path: /usr/bin/nvim }
  loop_control:
    loop_var: common_nvim_alt
  become: true


- name: Install file archiving tools
  ansible.builtin.apt:
    name:
      - pigz
      - pbzip2
      - zip
      - unzip
    state: present
  become: true

- name: Install backup tools
  ansible.builtin.apt:
    name:
      - borgbackup
    state: present
  become: true

- name: Install monitoring tools
  ansible.builtin.apt:
    name:
      - neofetch
      - atop
      - htop
      - dstat                         # system monitoring tool  (allows monitoring system resources such as cpu, memory, disk & network stats)
      - psmisc
      - iotop
      - powertop
      - sysstat                       # `sar`, `iostat`
      - smartmontools
      - hdparm
      - usbutils
    state: present
  become: true

- name: Install networking tools
  ansible.builtin.apt:
    name:
      - nmap
      - netcat
      - tcpdump
      - iproute2                      # `ip`;   NOTE: package 'net-tools' has been deprecated
      - dnsutils                      # `dig`
      - wget
      - curl
      - iperf
      - speedtest-cli
    state: present
  become: true

- name: Install administration tools
  ansible.builtin.apt:
    name:
      - sudo
      - aptitude
      - util-linux                    # Most likely already installed (contains MANY utilities)  (`lscpu``, `lspci``, ..)
      - software-properties-common    # abstraction of the used apt repositories (allows easily managing distribution & independent software vendor software sources)  -> `add-apt-repository`, `apt-add-repository`
      - needrestart                   # NOTE: 2 check whether reboot is pending: `sudo needrestart -r i`
      - ssh
      - mosh
      #- btrfs-progs
    state: present
  become: true

- name: Privacy tools
  block:
    - name: Install privacy tools
      ansible.builtin.apt:
        name:
          - ccrypt
          - cryptsetup
          - zerofree
        state: present

    - name: Install luks sparse file helper
      ansible.builtin.copy:
        src: bin/luks-sparse_helper
        dest: /usr/local/bin/luks-sparse_helper
        owner: root
        group: root
        mode: 0755
  become: true


- name: Install shell related tools
  ansible.builtin.apt:
    name:
      - moreutils
      - procps                        # `watch` command
      - pv
      - uuid
    state: present
  become: true


# (!!  ALSO REQUIRED FOR ZSH  !!)
- name: Install git
  ansible.builtin.apt:
    name:
      - git
      - git-lfs
    state: present
  become: true

#- name: Init git LFS for current user        # TODO: NOT  IDEMPOTENT ???
#  ansible.builtin.command: git lfs install
#  become: false


- ansible.builtin.include_tasks: '{{ item }}'
  loop:
    - package-python.yml
    - package-tmux.yml
    - package-zsh.yml
    - package-nala.yml
