---
- name: Install Python and tools
  block:
    - name: Python interpreter + pip
      ansible.builtin.apt:
        update_cache: true
        name:
          - python3-full
          - python3-pip
        state: present
    - name: Misc.
      ansible.builtin.apt:
        update_cache: true
        name:
          - python3-dev         # Required 4 extending Python interpreter or embedding Python in applications  (we care about the latter)
          - python3-psutil      # Required for `dconf` module
          - python3-apt         # Required by Ansible modules
        state: present
  become: true


- name: Update alternatives
  block:
    - name: Switch to python3
      community.general.alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3

    - name: Switch to pip3
      community.general.alternatives:
        name: pip
        link: /usr/bin/pip
        path: /usr/bin/pip3
  become: true


- name: Install pip packages
  block:
    - name: General packages
      ansible.builtin.pip:                    # NOTE: sudo installs it for ALL users (otherwise only local user)
        name:
          - pip-review                        # NOTE: 2 check for updates, use: `pip-review --local --auto`
        #extra_args: --break-system-packages   # TODO: Workaround 4 now
  become: false
