---
- name: Install Python and tools
  block:
    - name: Python interpreter + pip
      ansible.builtin.apt:
        update_cache: true
        name:
          - python3
          - python3-pip
        state: present
    - name: Dev libs
      ansible.builtin.apt:
        update_cache: true
        name:
          - python3-dev    # Required 4 extending Python interpreter or embedding Python in applications  (we care about the latter)
        state: present
  become: true


- name: Update alternatives
  block:
    - name: Switch to python3
      community.general.alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3

    - name: Switch to pip3
      community.general.alternatives:
        name: pip
        link: /usr/bin/pip
        path: /usr/bin/pip3
  become: true


- name: Install pip packages
  block:
    - name: General packages
      ansible.builtin.pip:   # NOTE: sudo installs it for ALL users (otherwise only local user)
        name:
          - pip-review              # NOTE: 2 check for updates, use: `pip-review --local --auto`
          # required by Ansible modules
          - psutil                  # Required for `dconf` module
    - name: Debian-based systems
      ansible.builtin.pip:   # NOTE: sudo installs it for ALL users (otherwise only local user)
        name:
          # required by Ansible modules
          - python-apt
      when: ansible_os_family == 'Debian'
  become: true
