---
- name: Create config dir
  ansible.builtin.file:
    path: '{{ docker_container.config_basedir }}/dl_services'
    state: directory
    mode: 0755
  become: false

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ docker_container.config_basedir }}/dl_services/docker-compose.yml'
    mode: 0640
  become: false

#- name: Ensure container is running
#  community.docker.docker_compose:
#    project_src: '{{ docker_container.config_basedir }}/dl_services/'
#    build: false
#  become: false
