---
- name: restart ssh daemon
  block:
    - name: restart ssh daemon
      ansible.builtin.service:
        name: ssh
        state: restarted
      when: ansible_facts.os_family != 'Darwin'
    - name: restart ssh daemon
      community.general.launchd:
        name: com.openssh.sshd
        state: restarted
      when: ansible_facts.os_family == 'Darwin'
  become: true


- name: dpkg-reconfigure keyboard-configuration
  command: /usr/sbin/dpkg-reconfigure -f noninteractive keyboard-configuration
  become: true
  when: ansible_os_family == 'Debian'



- name: rebuild fonts cache
  block:
    - name: rebuild fonts cache
      ansible.builtin.shell: 'fc-cache -v -f'
      when: ansible_facts.os_family != 'Darwin'
    - name: rebuild fonts cache
      ansible.builtin.debug:
        msg: …
      when: ansible_facts.os_family == 'Darwin'
  become: true
