---
- name: restart ssh daemon
  block:
    - name: '[Debian/Ubuntu]'
      ansible.builtin.service:
        name: sshd
        state: restarted
      when: ansible_facts.os_family != 'Darwin'
    - name: '[Darwin]'
      community.general.launchd:
        name: com.openssh.sshd
        state: restarted
      when: ansible_facts.os_family == 'Darwin'
  become: true


- name: dpkg-reconfigure keyboard-configuration
  command: /usr/sbin/dpkg-reconfigure -f noninteractive keyboard-configuration
  become: true
  when: ansible_os_family == 'Debian'
