---
- name: Enable other packages
  repace:
    path: /etc/apt/sources.list
    regexp: '^# deb-src'
    replace: 'deb-src'
  become: yes

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes
  become: yes



- name: Install file general purpose tools
  apt:
    name:
      - tree
      - rename
      - fdupes
      - dos2unix
    state: present
  become: yes

- name: Install file backup tools
  apt:
    name:
      - rclone
    state: present
  become: yes

- name: Install file archiving tools
  apt:
    name:
      - pigz
      - pbzip2
      - pxz
      - zip
      - unzip
    state: present
  become: yes

- name: Install monitoring tools
  apt:
    name:
      - neofetch
      - htop
      - pstree
      - iotop
      - sysstat
      - smartmontools
      - hdparm
      - usbutils
    state: present
  become: yes

- name: Install networking tools
  apt:
    name:
      - nmap
      - speedtest-cli
      - net-tools
      - wget
    state: present
  become: yes

- name: Install administration tools
  apt:
    name:
      - mosh
      #- unattended-upgrades
    state: present
  become: yes

- name: Install privacy tools
  apt:
    name:
      - ccrypt
      - cryptsetup
      - zerofree
    state: present
  become: yes

- name: Install shell related tools
  apt:
    name:
      - moreutils
      - watch
      - pv
      - uuid
    state: present
  become: yes

- name: Install dev tools
  apt:
    name:
      - git
    state: present
  become: yes

- name: Install runtimes
  apt:
    name:
      - python3
    state: present
  become: yes




- name: Install docker
  pip:
    name: docker
    state: latest
  become: yes
