---
- name: Install Python 3
  apt:
    name:
      - python3
    state: present

- name: Switch to pip3
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3

- name: Switch to python3
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

# NOTE: 2 check for updates, use: `pip-review --local --auto`
- name: Install pip-review python package
  pip:
    name: pip-review
