---
- name: Copy config file
  copy:
    src: 'tmux.conf'
    dest: '/home/{{ user_name }}/.tmux.conf'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644

- name: Install tmux
  apt:
    name:
      - tmux
    state: present
