---
- name: 'Check if GNOME is used as desktop environment  (TODO: revise)'
  ansible.builtin.command: which gsettings
  failed_when: false
  changed_when: false
  check_mode: false
  when: gather_workstation_facts is not defined
  register: result_gnome_command
  become: false


# --  Set workstation facts  --
- name: Set variables (as facts)
  ansible.builtin.set_fact:
    desktop_envs: "{{ ['GNOME' if result_gnome_command.rc == 0] }}"
    firefox_package_name: firefox #"{{ 'firefox-esr' if ansible_facts.distribution == 'Debian' else 'firefox' }}"
    gather_workstation_facts: True
  when: gather_workstation_facts is not defined
  become: false


#-  ansible.builtin.debug:
#    msg: desktop_envs={{ desktop_envs }}
