---
- name: Install cert-gen script
  copy:
    src: 'ssl-certgen'
    dest: '/usr/bin/ssl-certgen'
    owner: 'root'
    group: 'root'
    mode: 0644
  become: true


- name: Ensure data dir exists
  ansible.builtin.file:
    path: '{{ docker_container_data_basedir }}/{{ container_name }}'
    state: directory
    mode: 0755
  become: false

- name: Create config dir
  ansible.builtin.file:
    path: '{{ docker_container_config_basedir }}/{{ container_name }}'
    state: directory
    mode: 0755
  become: false

- name: Copy config file
  copy:
    src: 'dynamic-conf.yml'
    dest: '{{ docker_container_config_basedir }}/{{ container_name }}/dynamic-conf.yml'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
  become: false

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ docker_container_config_basedir }}/{{ container_name }}/docker-compose.yml'
    mode: '0640'
  become: false
  #notify: Restart pi-hole

- name: Ensure container is running
  community.docker.docker_compose:
    project_src: '{{ docker_container_config_basedir }}/{{ container_name }}/'
    build: false
  become: false
