---
- name: Install unattended upgrades package
  ansible.builtin.package:
    name: unattended-upgrades
    state: present
  become: true

- name: 'Remove default config  (TODO: check / revise)'
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    state: absent
  become: true


# NOTE: To debug, use `sudo unattended-upgrade --debug --dry-run`
#       Log file: `cat /var/log/unattended-upgrades/unattended-upgrades.log`
- name: Copy unattended-upgrades configuration files in place
  ansible.builtin.template:
    src: 'unattended-upgrades/{{ unattended_update_config_file }}.j2'
    dest: '/etc/apt/apt.conf.d/{{ unattended_update_config_file }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - 02confirmconfchanges
    - 10periodic
    - 50unattended-upgrades
  loop_control:
    loop_var: unattended_update_config_file
  become: true
