---
# Check runlevel: `systemctl get-default`  //  Change runlevel: `systemctl set-default multi-user.target`  (runlevels: multi-user.target, graphical.target)
- name: Change default target to multi-user.target
  file:
    src: /usr/lib/systemd/system/multi-user.target
    dest: /etc/systemd/system/default.target
    state: link


- include_tasks: config-unattended_updates.yml


- name: Install login system stats script
  ansible.builtin.copy:
    src: scripts/zprofile
    dest: /etc/zsh/zprofile
    owner: root
    group: root
    mode: 0644
