---
- name: Install login system stats script
  ansible.builtin.copy:
    src: 10-show_system_info
    dest: /etc/zsh/zprofile
    owner: root
    group: root
    mode: 0644

- include_tasks: unattended-updates.yml
