---
- name: Install login system stats script
  copy:
    src: "10-show_system_info"
    dest: "/etc/zsh/zprofile"
    owner: root
    group: root
    mode: 0644

- include_tasks: unattended-updates.yml


- name: Install git
  apt:
    name:
      - git
      - git-lfs
    state: present

#- name: Init git LFS for current user        # TODO: NOT  IDEMPOTENT ???
#  command: git lfs install
#  become: false
