---
- name: Install unattended upgrades package
  become: true
  ansible.builtin.package:
    name: unattended-upgrades
    state: present

- name: Remove default config  ??
  become: true
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    state: absent


- name: Check if Docker is installed
  ansible.builtin.command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: result_docker_command

# NOTE: To debug, use `sudo unattended-upgrade --debug --dry-run`
#       Log file: `cat /var/log/unattended-upgrades/unattended-upgrades.log`
- name: Copy unattended-upgrades configuration files in place
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
