---
# SEE ALSO: https://github.com/stkrzysiak/windows-playbook-scoop/blob/master/tasks/explorer.yml

- name: 'Set Explorer "start page" 2 the Computer view'
  include_tasks: reg_hkcu_default_user.yml
  vars:
    reg_hkcu_keys:
      - path_wo_hkcu: Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: LaunchTo
        data: 1
        type: dword

- name: Show file extensions
  include_tasks: reg_hkcu_default_user.yml
  vars:
    reg_hkcu_keys:
      - path_wo_hkcu: Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: HideFileExt
        data: 0
        type: dword

- name: Show Hidden & System Files
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item }}"
    data: 1
    type: dword
  loop:
    - Hidden
    - ShowSuperHidden
