---
- name: List View
  include_tasks: reg_hkcu_default_user.yml
  vars:
    reg_hkcu_keys:
      - path_wo_hkcu: Software\Microsoft\Windows\CurrentVersion\Start
        name: AllAppsViewMode
        data: 2
        type: dword

- name: Disable Start Menu Tips & Recommendations
  include_tasks: reg_hkcu_default_user.yml
  vars:
    reg_hkcu_keys:
      - path_wo_hkcu: Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: Start_IrisRecommendations
        data: 0
        type: dword

- name: Default pinned apps
  block:
    - ansible.windows.win_file:
        path: C:\Users\Default\AppData\Local\Microsoft\Windows\Shell
        state: directory
    - ansible.windows.win_copy:
        src: files/LayoutModification.json
        dest: C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\LayoutModification.json
