---
# Node settings
- name: Set timezone
  ansible.windows.win_timezone:
    timezone: "{{ win_timezone }}"

- name: Set computer name
  ansible.windows.win_hostname:
    name: "{{ win_hostname }}"
  register: hostname_change
  when: win_hostname is defined
# TODO:
#- name: Reboot the machine if the name was changed
#  ansible.windows.win_reboot:
#  when:
#    - win_hostname is defined
#    - hostname_change.reboot_required

# Power settings     TODO: Not idempotent
- name: Disable hibernation
  ansible.windows.win_powershell:
    script: |
      powercfg -h off
  when: ansible_facts['virtualization_role'] == 'guest'

- name: Disable display timeout
  ansible.windows.win_powershell:
    script: |
      powercfg -change -monitor-timeout-ac 0
      powercfg -change -monitor-timeout-dc 0
  when: ansible_facts['virtualization_role'] == 'guest'

- name: Disable sleep
  ansible.windows.win_powershell:
    script: |
      powercfg -change standby-timeout-ac 0
      powercfg /change standby-timeout-dc 0
  when: ansible_facts['virtualization_role'] == 'guest'

# TODO: Disk timeout (`powercfg /change disk-timeout-ac 0` & `powercfg /change disk-timeout-dc 0`)

# Personalization
- name: Global - Windows Lock Screen
  block:
  - name: Disable Windows Lock Screen
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
      name: NoLockScreen
      data: 1
      type: dword
      state: present
  - name: Disable Slideshows
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
      name: NoLockScreenSlideshow
      data: 1
      type: dword
      state: present

# M$ stuff
- name: Global - Windows Spotlight
  block:
    - name: Disable Windows Spotlight features
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent
        name: DisableWindowsSpotlightFeatures
        data: 1
        type: dword
        state: present
    - name: Turn off Spotlight collection on Desktop
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent
        name: ConfigureWindowsSpotlight
        data: 2
        type: dword
        state: present
    - name: Force a single static wallpaper image to prevent user-driven slideshows
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\PersonalizationCSP
        name: DesktopImagePath
        data: 'C:\Windows\Web\Wallpaper\Windows\img0.jpg'
        type: string
        state: present

- name: Global - OneDrive
  block:
    - name: Prevent the usage of OneDrive for file storage
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive
        name: DisableFileSyncNGSC
        data: 1
        type: dword
        state: present
    - name: Remove OneDrive icon from File Explorer navigation pane
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive
        name: DisableFileSync
        data: 1
        type: dword
        state: present
    - name: Block OneDrive network traffic before user sign-in
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\OneDrive
        name: PreventNetworkTrafficPreUserSignIn
        data: 1
        type: dword
        state: present

- name: Global - M$ Account
  block:
    - name: 'M$ Account: Block users from adding or logging in'
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: NoConnectedUser   # NOTE: Works only in Education/Enterprise edition
        data: 3
        type: dword
        state: present
    - name: 'M$ Account: Disable M$ Account Sign-in Assistant service'
      ansible.windows.win_service:
        name: wlidsvc
        start_mode: disabled
        state: stopped

- name: Global - M$ Store
  block:
    - name: 'M$ Store: Turn off'
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore
        name: RemoveWindowsStore   # NOTE: Works only in Education/Enterprise edition
        data: 1
        type: dword
        state: present
    - name: 'M$ Store: Block from offering or updating apps'
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore
        name: DisableStoreApps
        data: 1
        type: dword
        state: present
    - name: 'M$ Store: Turn off automatic download & install of updates'
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore
        name: AutoDownload
        data: 2  # 2 explicitly disables automatic updates
        type: dword
        state: present
