---
#- name: Show icons
#  ansible.windows.win_regedit:
#    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel
#    name: "{{ item }}"
#    data: 0
#    type: dword
#  loop:
#    - "{20D04FE0-3AEA-1069-A2D8-08002B30309D}" # This PC
#    - "{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}" # Network
#    - "{645FF040-5081-101B-9F08-00AA002F954E}" # Recycle Bin

- name: Set solid color wallpaper
  block:
    - name: Disable intune restrictions
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\PersonalizationCSP
        name: DesktopImagePath
        #data: 'C:\Windows\Web\Wallpaper\Windows\img0.jpg'
        type: string
        state: absent
    - name: Turn off standard wallpaper image policy globally
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
        name: Wallpaper
        #data: ""
        type: string
        state: absent
    #
    - name: Clear current wallpaper + Set solid colors
      include_tasks: reg_hkcu_default_user.yml
      vars:
        reg_hkcu_keys:
          - path_wo_hkcu: Control Panel\Desktop
            name: WallPaper
            data: ""
            type: string
          - path_wo_hkcu: Control Panel\Colors
            name: Background
            data: "0 120 215"  # 240 240 240 = Light Gray, 0 0 0 = Black, 0 120 215 = Windows Blue
            type: string
          - path_wo_hkcu: Control Panel\Desktop
            name: Background
            data: "0 120 215"
            type: string
