---
- ansible.builtin.include_tasks: "{{ task_name }}"
  loop:
    - config-general.yml
    - config-locale.yml
    - config-power.yml
    - config-shell-audio.yml
    - config-shell-desktop.yml
    - config-shell-explorer.yml
    - config-shell-misc.yml
    - config-shell-start.yml
    - config-shell-taskbar.yml
    - config-shell-winlogon.yml
    #- config-storage.yml  # TODO: Doesn't set the values, but claims to do so
    - config-win_bloat.yml
    - config-wpa.yml
    #
    - packages-choco.yml
    - packages-choco_desktop.yml
    - packages-win_bloat.yml
  loop_control:
    loop_var: task_name
