---
- name: Ensure Chocolatey is installed
  win_chocolatey:
    name:
      - chocolatey
      - chocolateygui
    state: present

## Prereqs.
#- name: Win32-OpenSSH service - install
#  block:
#    - win_chocolatey:
#        name: openssh
#        package_params: /SSHServerFeature
#        state: present
#    # set the default shell to PowerShell
#    - win_regedit:
#        path: HKLM:\SOFTWARE\OpenSSH
#        name: DefaultShell
#        data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
#        type: string
#        state: present

- name: Install Office packages
  win_chocolatey:
    name:
      - caesium.install
      - InkScape
      - imageglass
      - file-converter
      - drawio
      - obs-studio.install
      - vlc.install
      - thunderbird
      - sumatrapdf.install
      - pdftkbuilder
    state: present

- name: Install HW Monitoring Tools II
  win_chocolatey:
    name:
      - libreoffice-fresh
      - digikam
    state: present
  when: ansible_facts['virtualization_role'] != 'guest'

- name: Install PowerUser packages
  win_chocolatey:
    name:
      - 7zip.install
      - bleachbit.install
      - autoruns
      - hashtab
      - notepadplusplus.install
      - procexp  # Causes checksum issues
      - WinDirStat
      - powertoys
    ignore_checksums: True
    state: present

- name: Install Maintenance packages
  win_chocolatey:
    name:
      - bulk-crap-uninstaller   # TODO: Doesn't work
      - shutup10
    state: present
  #become: true
  #become_user: Administrator
  #become_method: runas

- name: Install HW Monitoring Tools
  win_chocolatey:
    name:
      - crystaldiskinfo # crystaldiskinfo.portable
      - crystaldiskmark
      - coretemp
      - cpu-z.install
      - gpu-z
    state: present
  when: ansible_facts['virtualization_role'] != 'guest'

- name: Install Devel packages
  win_chocolatey:
    name:
      - hxd
      - python3
    state: present

- name: Install Services/Misc. packages
  win_chocolatey:
    name:
      - wireguard
      - rustdesk.install
      - keepassx
      - kindle
      #- lghub
    state: present
  when: ansible_facts['virtualization_role'] != 'guest'
