---
- name: restart docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true


- name: restart networking daemon
  ansible.builtin.service:
    name: networking
    state: restarted
  become: true
