---
- name: restart docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted


- name: restart network daemon
  ansible.builtin.service:
    name: networking
    state: restarted
