---
- name: Configure
  block:
    - name: Set config as vars
      ansible.builtin.set_fact:
        firefox_profiles:
          default:
            extensions:
              # URL on addons.mozilla.org
              - video-downloader-profession
              - video-downloadhelper
              - buster-captcha-solver
              - duplicate-tabs-closer

    - name: "Run 'staticdev.firefox' role"
      ansible.builtin.include_role:
        name: staticdev.firefox
  become: false


- name: Install dependencies for extension
  # Equivalent command: `dpkg -s net.downloadhelper.coapp`
  block:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Install if not yet installed
      block:
        - name: Download package as deb
          ansible.builtin.get_url:
            # TODO: Always fetch latest version
            url: 'https://github.com/mi-g/vdhcoapp/releases/download/v{{ downloadhelper_coapp_ver }}/net.downloadhelper.coapp-{{ downloadhelper_coapp_ver }}-1_{{ cpu_arch }}.deb'
            dest: '/tmp/net.downloadhelper.coapp-{{ downloadhelper_coapp_ver }}-1_{{ cpu_arch }}.deb'
          become: false

        - name: Install it
          # Equivalent command: `sudo apt install ./name.deb`
          ansible.builtin.apt:
            deb: '/tmp/net.downloadhelper.coapp-{{ downloadhelper_coapp_ver }}-1_{{ cpu_arch }}.deb'
          become: true
      when:
        - ansible_os_family == 'Debian'
        - "'net.downloadhelper.coapp' not in ansible_facts.packages"
