---
- name: '[Darwin / Debian/Ubuntu] Install CLI tools'
  block:
    - ansible.builtin.package:
        name:
          - exiftool
          - ffmpeg
          - gifsicle
          - imagemagick
      become: '{{ package_manager_become }}'

    - name: Install yt-dlp
      community.general.pipx:
        name: yt-dlp
        state: latest
        install_deps: true
        executable: pipx
      become: false


- name: Install video players
  block:
    - name: '[Darwin] Install homebrew packages'
      ansible.builtin.include_tasks: ../../base/tasks/darwin/homebrew_casks.yml
      vars:
        packages_homebrew_casks:         # TODO: Add flatpak counterparts 4 linux & check whether VM
          - dir: Video
            packages:
              - iina
              - vlc
    - name: '[Debian/Ubuntu] Install flatpak packages'
      community.general.flatpak:
        name:
          - org.videolan.VLC
          - io.github.celluloid_player.Celluloid
        state: present
      become: true
      when: ansible_facts.os_family != 'Darwin'
