---
- name: restart docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true



- name: restart networking service
  block:
    - name: restart networking daemon
      ansible.builtin.service:
        name: networking
        state: restarted
      when: ansible_facts.os_family == 'Debian'

    - name: restart networking daemon
      ansible.builtin.service:
        name: systemd-networkd
        state: restarted
      when: ansible_facts.distribution == 'Ubuntu'
  become: true




# ------------------------------------------------------------------------------------------------------
- name: restart dhcpcd service
  ansible.builtin.service:
    name: dhcpcd
    state: restarted
  become: true
