---
- name: restart docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true



- name: restart networking daemon
  ansible.builtin.service:
    name: '{{ networking_service }}'
    state: restarted
  become: true




# ------------------------------------------------------------------------------------------------------
- name: restart dhcpcd service
  ansible.builtin.service:
    name: dhcpcd
    state: restarted
  become: true
