---
- name: Copy docker daemon IPv6 config file
  ansible.builtin.copy:
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:abc1::/64"
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker daemon
  become: true

# Equivalent command: `docker network create --subnet="2001:db8:1::/64" --ipv6 traefik`
- name: Create a network w/ IPv6 IPAM config
  community.docker.docker_network:
    name: '{{ docker_default_network }}'
    enable_ipv6: true
    ipam_config:
      - subnet: 2001:db8:1::/64
  become: false


# Fix routing (since we use internally private IPv6 addresses which are NOT routable)
- name: Install iptables
  ansible.builtin.apt:
    name:
      - iptables
      - iptables-persistent
    state: present
  become: true

# Equivalent command  (+ persist):
#   `ip6tables -t nat -A POSTROUTING -s 2001:db8:1::/64 ! -o docker0 -j MASQUERADE`
#   `sudo sh -c "ip6tables-save > /etc/iptables/rules.v6"`
# Validation: `docker run --network=reverse_proxy --rm -t busybox ping6 -c 4 google.com`
- name: Copy iptable config tables
  ansible.builtin.copy:
    content: |
      *nat
      :PREROUTING ACCEPT [3537:366712]
      :INPUT ACCEPT [1428:179948]
      :OUTPUT ACCEPT [51:5820]
      :POSTROUTING ACCEPT [46:5420]
      -A POSTROUTING -s 2001:db8:1::/64 ! -o docker0 -j MASQUERADE
      -A POSTROUTING -s 2001:db8:abc1::/64 ! -o docker0 -j MASQUERADE
      COMMIT
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: 0644
  notify: restart networking daemon
  become: true
