---
- ansible.builtin.include_tasks: install.yml



# ------------------------------------------------------------------------------------------------------
- ansible.builtin.include_tasks: config-ipv6.yml
  when: "'dns_servers' in group_names  or  'home_servers' in group_names"








# ------------------------------------------------------------------------------------------------------
- name: "[dhcpcd5] FIX: Docker related issue  (https://github.com/raspberrypi/linux/issues/4092; TODO: CHECK WHETHER ISSUE STILL PERSISTS)"
  ansible.builtin.lineinfile:
    state: present
    line: "denyinterfaces veth*               # Temporary workaround for issue: https://github.com/raspberrypi/linux/issues/4092"
    path: /etc/dhcpcd.conf
    insertbefore: BOF                         # Necessary, otherwise inserted after e.g., config for interface
  notify: restart dhcpcd service
  when: "'rpis' in group_names  and  ansible_facts.distribution == 'Debian'"
  become: true
