---
- name: "[Debian/Ubuntu] Install"
  ansible.builtin.apt:
    name:
      - zsh
    state: present
  when: ansible_facts.os_family != 'Darwin'
  become: true

- name: Create zsh config dir
  ansible.builtin.file:
    path: "/{{ os_homedir }}/{{ user.name }}/.config/zsh/"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group_name }}"
    mode: 0755
  become: false

- name: Install oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/{{ os_homedir }}/{{ user.name }}/.config/zsh/.oh-my-zsh/"
    clone: true
    depth: 1
    update: true
  become: false

- name: Install oh-my-zsh plugins
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/{{ plugin }}"
    dest: "/{{ os_homedir }}/{{ user.name }}/.config/zsh/.oh-my-zsh/custom/plugins/{{ plugin }}/"
    clone: true
    depth: 1
    update: true
  with_items:
    - "zsh-syntax-highlighting"
    - "zsh-autosuggestions"
  loop_control:
    loop_var: plugin
  become: false

- name: "[Linux] Install fonts for Powerlevel10k theme (ONLY required when using Terminal Emulators in Desktop environments)"
  ansible.builtin.apt:
    name:
      - fonts-powerline
    state: present
  when: ansible_facts.os_family != 'Darwin'
  become: true

- name: Install Powerlevel10k theme
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "/{{ os_homedir }}/{{ user.name }}/.config/zsh/.oh-my-zsh/custom/themes/powerlevel10k/"
    clone: true
    depth: 1
    update: true
  become: false

- name: Copy config files (I)
  ansible.builtin.template:
    src: "{{ config_file.src }}"
    dest: "/{{ os_homedir }}/{{ user.name }}/.config/zsh/{{ config_file.dest_file }}"
    owner: "{{ user.name }}"
    group: "{{ user.group_name }}"
    mode: 0644
  with_items:
    - src: "zsh/zshenv.j2"
      dest_file: ".zshenv"
    - src: "zsh/p10k.j2"
      dest_file: ".p10k.zsh" # 'Generated' using `p10k configure` (and just copied)
  loop_control:
    loop_var: config_file
  become: false

- name: Copy config files (II)
  ansible.builtin.template:
    src: "{{ config_file.src }}"
    dest: "/{{ os_homedir }}/{{ user.name }}/.config/zsh/{{ config_file.dest_file }}"
  with_items:
    - src: "zsh/lscolors.sh.j2"
      dest_file: "lscolors.sh"
    - src: "zsh/zshrc.j2"
      dest_file: ".zshrc"
  loop_control:
    loop_var: config_file
  become: false

- name: Set config dir
  ansible.builtin.file:
    src: "/{{ os_homedir }}/{{ user.name }}/.config/zsh/.zshenv"
    dest: "/{{ os_homedir }}/{{ user.name }}/.zshenv"
    state: link
  become: false

- name: Change shell
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: /bin/zsh
  become: true

# GNU/Linux: `/etc/environment`, `/etc/profile.d`
# ( NOTE: Darwin: `/etc/paths`, `/etc/paths.d/` )
# TODO: Add the following paths on Debian (which are "present" on Ubuntu)
#   - /usr/local/sbin
#   - /usr/sbin
#   - /sbin
