---
- include_tasks: security.yml

- name: Allow client to pass locale environment variables
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AcceptEnv LANG LC_\*$'
    line: "AcceptEnv LANG LC_*"
    validate: '/usr/sbin/sshd -T -f %s'

- name: Restart ssh dasemon
  service:
    name: sshd
    state: restarted
