---
- name: "Copy default suggested bookmarks  (TODO: AUTO IMPORT INTO FF  !!)"
  ansible.builtin.copy:
    src: firefox-devel_bookmarks.json
    dest: "/{{ os_homedir }}/{{ user.name }}/.local/share/.firefox-default_devel_bookmarks.json"
  become: false

- name: Autostart Firefox on login
  ansible.builtin.file:
    src: /usr/share/applications/firefox.desktop
    dest: "/{{ os_homedir }}/{{ user.name }}/.config/autostart/firefox.desktop"
    state: link
  become: false
