---
# --  Ubuntu Firefox  --
# TODO: (CURRENTLY 4 UBUNTU: temporary workaround to ensure on Ubuntu apt-version gets installed (better performance + 3rd party integrations like video download plugins))  --
- name: "Ubuntu - Ensure no Firefox snap is / will be installed"
  block:
    - name: Add apt signing key
      # NOTE: Equivalent command: `wget -O - https://packages.mozilla.org/apt/repo-signing-key.gpg | sudo apt-key add -`; Show keys: `apt-key list`
      ansible.builtin.get_url:
        url: https://packages.mozilla.org/apt/repo-signing-key.gpg
        dest: /etc/apt/trusted.gpg.d/packages.mozilla.org.asc
        mode: "0644"
        force: true

    - name: Add apt repo and update cache
      # NOTE: Equivalent command: `sudo add-apt-repository 'deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main'`
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main"
        filename: mozilla
        state: present
        update_cache: true

    # CHECK via: `apt-cache policy`  ('Pin-Priority': https://wiki.ubuntuusers.de/Apt-Pinning/#Werte-fuer-Pin-Priority)
    - name: Pin apt repo
      block:
        - ansible.builtin.set_fact:
            apt_pin_packages:
              - target: "origin packages.mozilla.org"
                priority: 1001
              - name: "firefox*"
                target: "release o=Ubuntu"
                priority: -1
        - ansible.builtin.template:
            src: linux/apt-pin.pref.j2
            dest: /etc/apt/preferences.d/mozilla-firefox.pref
            owner: root
            group: root
            mode: 0644

    - name: Install
      ansible.builtin.apt:
        name: firefox

    #TODO -- UNATTENDED UPGRADES: echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
  when: ansible_facts.distribution == 'Ubuntu'
  become: true
