---
- name: conky - Install
  ansible.builtin.apt:
    name: conky-all
    state: present
  become: true


- name: conky - Copy config file
  ansible.builtin.template:
    src: linux/conkyrc.j2
    dest: '/home/{{ user.name }}/.conkyrc'
    owner: '{{ user.name }}'
    group: '{{ user.group_name }}'
    mode: 0644
  become: false


- name: conky - Create autostart dir
  ansible.builtin.file:
    path: '/home/{{ user.name }}/.config/autostart/'
    state: directory
    owner: '{{ user.name }}'
    group: '{{ user.group_name }}'
    mode: 0755
  become: false

- name: conky - Create autostart entry
  ansible.builtin.template:
    src: linux/conky.desktop.j2           # TODO: INLINE ONCE SUPPORTED BY MODULE
    dest: '/home/{{ user.name }}/.config/autostart/conky.desktop'
    owner: '{{ user.name }}'
    group: '{{ user.group_name }}'
    mode: 0644
  become: false
