#!/usr/bin/env ansible-playbook
---
- hosts: all
  roles:
    - role: common_base
      tags:
        - common_base


# --  "HW specific"  --
- hosts: hw_specific
  roles:
    - role: hw_specific
      tags:
        - hw_specific


# --  "System specific"  --
- hosts: workstations, dev_workstations, il_workstations
  roles:
    - role: common_extended
    - role: workstation/base
  vars:
    dock_favorite_apps:
      - "'org.gnome.Nautilus.desktop'"
      - "'firefox.desktop'"
      - "'brave-browser.desktop'"
      - "'codium.desktop'"
      - "'terminator.desktop'"
      - "'gnome-system-monitor.desktop'"
  tags: workstation

- hosts: dev_workstations
  roles:
    - role: workstation/dev_workstation
      tags:
        - dev_workstation
#    - role: docker
#      tags:
#        - docker
  vars:
#    gnome_wallpaper: win10-jobs.jpg
    firefox_profiles:
      default:
        extensions:
          - umatrix
          - privacy-redirect
          - darkreader
          - save-page-we

- hosts: il_workstations
  roles:
    - role: workstation/il_workstation
      tags:
        - il_workstation


- hosts: servers, dev_servers, home_servers
  roles:
    - role: server/base
      tags: server

- hosts: dev_servers
  roles:
    - role: common_extended
    - role: server/dev_server
  tags:
    - dev_server

- hosts: home_servers
  vars:
    docker_container:
      data_basedir: /home/{{ user.name }}/homeserver/data/
      config_basedir: /home/{{ user.name }}/homeserver/config/
  roles:
  # -- Docker containers --
    - role: 3rd-party/internet-pi
      tags:
        - inet_monitoring

    - role: server/home_server/containers/
      tags:
        - containers
  tags:
    - home_server
