---
collections:
  - name: community.general
  - name: community.docker

roles:
  - name: chriswayg.msmtp-mailer            # Required 4 mail notifications
  - name: staticdev.firefox
  - name: petermosmans.customize-gnome
