---
- hosts: all
  become: true
  roles:
    - role: common
      tags:
        - common


# --  "HW specific"  --
- hosts: rpis
  become: true
  roles:
    - role: hw-specific/rpi
      tags:
        - rpi

- hosts: vmware_vms
  become: true
  roles:
    - role: hw-specific/vmware
      tags:
        - vmware


# --  "System specific"  --
- hosts: workstations, office_workstations, dev_workstations
  become: true
  roles:
    - role: workstation/base
      tags:
        - workstation

- hosts: office_workstations
  become: true
  roles:
    - role: workstation/office_workstation
      tags:
        - workstation
        - office_workstation

- hosts: dev_workstations
  become: true
  roles:
    - role: workstation/dev_workstation
      tags:
        - workstation
        - dev_workstation
    - role: docker
      tags:
        - docker


- hosts: servers, home_servers
  become: true
  roles:
    - role: server/base
      tags:
        - server
        - home_server
    - role: docker
      tags:
        - docker

- hosts: home_servers
  vars:
    docker_container_data_basedir: /home/{{ user_name }}/homeserver_data/container_data
    docker_container_config_basedir: /home/{{ user_name }}/homeserver_config/container_config
  roles:
    - role: server/home_server/base
      tags:
        - home_server
    - role: server/home_server/containers/bitwarden
      tags:
        - home_server
        - bitwarden
    - role: server/home_server/containers/nginx-helloworld
      tags:
        - home_server
        - testing
    - role: server/home_server/containers/pihole
      tags:
        - home_server
        - pihole
    - role: server/home_server/containers/portainer
      tags:
        - home_server
        - portainer

# KEEP IN MIND: Only run samba - OR - filebrowser (otherwise weird behvaior when using simultaneously)
    - role: server/home_server/containers/filebrowser
      tags:
        - home_server
        - filebrowser
    - role: server/home_server/containers/samba
      tags:
        - home_server
        - samba

    - role: server/home_server/containers/traefik
      tags:
        - home_server
        - traefik
    - role: server/home_server/containers/transmission
      tags:
        - home_server
        - transmission
    - role: server/home_server/containers/volact
      tags:
        - home_server
        - volact
    - role: server/home_server/containers/watchtower
      tags:
        - home_server
        - watchtower
