---
- hosts: all
  become: true
  roles:
    - role: base
      tags:
        - base

- hosts: workstations
  become: true
  roles:
    - role: workstation
      tags:
        - workstation

- hosts: servers
  become: true
  roles:
    - role: server
      tags:
        - server
        - homeserver

    - role: docker
      tags:
        - docker

- hosts: homeservers
  roles:
    - role: homeserver/base
      tags:
        - homeserver
    - role: homeserver/containers/bitwarden
      tags:
        - homeserver
        - bitwarden
    - role: homeserver/containers/filebrowser
      tags:
        - homeserver
        - filebrowser
    - role: homeserver/containers/pihole
      tags:
        - homeserver
        - pihole
    - role: homeserver/containers/portainer
      tags:
        - homeserver
        - portainer
    - role: homeserver/containers/rpi-pwm
      tags:
        - homeserver
        - rpi-pwm
    - role: homeserver/containers/samba
      tags:
        - homeserver
        - samba
    - role: homeserver/containers/traefik
      tags:
        - homeserver
        - traefik
    - role: homeserver/containers/transmission
      tags:
        - homeserver
        - transmission
    - role: homeserver/containers/volact
      tags:
        - homeserver
        - volact
    - role: homeserver/containers/watchtower
      tags:
        - homeserver
        - watchtower


- hosts: rpis
  become: true
  roles:
    - role: rpi
      tags:
        - rpi

- hosts: vmware_vms
  become: true
  roles:
    - role: vmware
      tags:
        - vmware
