---
- hosts: all
  become: true
  roles:
    - role: common
      tags:
        - common


# --  "HW specific" stuf  --
- hosts: rpis
  become: true
  roles:
    - role: hw-specific/rpi
      tags:
        - rpi

- hosts: vmware_vms
  become: true
  roles:
    - role: hw-specific/vmware
      tags:
        - vmware


# --  "System specific"  --
- hosts: workstations
  become: true
  roles:
    - role: workstation/base
      tags:
        - workstation

- hosts: servers
  become: true
  roles:
    - role: server/base
      tags:
        - server
        - homeserver
    - role: docker
      tags:
        - docker

- hosts: homeservers
  roles:
    - role: server/homeserver/base
      tags:
        - homeserver
    - role: server/homeserver/containers/bitwarden
      tags:
        - homeserver
        - bitwarden
    - role: server/homeserver/containers/nginx-helloworld
      tags:
        - homeserver
        - testing
    - role: server/homeserver/containers/pihole
      tags:
        - homeserver
        - pihole
    - role: server/homeserver/containers/portainer
      tags:
        - homeserver
        - portainer
#    - role: server/homeserver/containers/filebrowser
#      tags:
#        - homeserver
#        - filebrowser
    - role: server/homeserver/containers/samba
      tags:
        - homeserver
        - samba
    - role: server/homeserver/containers/traefik
      tags:
        - homeserver
        - traefik
    - role: server/homeserver/containers/transmission
      tags:
        - homeserver
        - transmission
    - role: server/homeserver/containers/volact
      tags:
        - homeserver
        - volact
    - role: server/homeserver/containers/watchtower
      tags:
        - homeserver
        - watchtower
