---
- hosts: all
  roles:
    - role: common
      tags:
        - common


# --  "HW specific"  --
- hosts: rpis
  roles:
    - role: hw_specific/rpi
      tags:
        - rpi

- hosts: vmware_vms
  roles:
    - role: hw_specific/vmware
      tags:
        - vmware


# --  "System specific"  --
- hosts: workstations, dev_workstations
  roles:
    - role: workstation/base
  tags: workstation
  vars:
    dock_favorite_apps:
      - "'org.gnome.Nautilus.desktop'"
      - "'{{ firefox_package_name }}.desktop'"
      - "'codium.desktop'"
      - "'terminator.desktop'"
      - "'gnome-system-monitor.desktop'"

- hosts: dev_workstations
  roles:
    - role: workstation/dev_workstation
      tags:
        - dev_workstation
    - role: docker
      tags:
        - docker
  vars:
    gnome_wallpaper: win10-jobs.jpg
    firefox_profiles:
      default:
        extensions:
          - umatrix
          - privacy-redirect
          - darkreader
          - save-page-we

- hosts: il_workstations
  roles:
    - role: workstation/il_workstation
      tags:
        - il_workstation


- hosts: servers, dev_servers, home_servers
  roles:
    - role: server/base
      tags:
        - server
        - home_server
    - role: docker
      tags:
        - docker
  vars:
    autoupdate_reboot_enabled: false

- hosts: dev_servers
  roles:
    - role: server/dev_server
  tags:
    - dev_server

- hosts: dns_servers
  roles:
    - role: server/dns_server
  tags:
    - dns_server

- hosts: home_servers
  vars:
    docker_container_data_basedir: /home/{{ user_name }}/homeserver_data/container_data
    docker_container_config_basedir: /home/{{ user_name }}/homeserver_config/container_config
  roles:
    - role: server/home_server/base
  # -- Docker containers --
    - role: server/home_server/containers/bitwarden
      tags:
        - bitwarden
    - role: server/home_server/containers/nginx-helloworld
      tags:
        - testing
    - role: server/home_server/containers/portainer
      tags:
        - portainer

# KEEP IN MIND: Only run samba - OR - filebrowser (otherwise weird behvaior when using simultaneously)
    - role: server/home_server/containers/filebrowser
      tags:
        - filebrowser
    - role: server/home_server/containers/samba
      tags:
        - samba

    - role: server/home_server/containers/traefik
      tags:
        - traefik
    - role: server/home_server/containers/transmission
      tags:
        - transmission
    - role: server/home_server/containers/volact
      tags:
        - volact
    - role: server/home_server/containers/watchtower
      tags:
        - watchtower
  tags:
    - home_server
