---
- hosts: all
  become: true
  roles:
    - role: common
      tags:
        - common


# --  "HW specific"  --
- hosts: rpis
  become: true
  roles:
    - role: hw-specific/rpi
      tags:
        - rpi

- hosts: vmware_vms
  become: true
  roles:
    - role: hw-specific/vmware
      tags:
        - vmware


# --  "System specific"  --
- hosts: workstations, dev_workstations
  roles:
    - role: workstation/base
      become: true
  tags: workstation
  vars:
    dock_favorite_apps:
      - "'org.gnome.Nautilus.desktop'"
      - "'{{ firefox_package_name }}.desktop'"
      - "'codium.desktop'"
      - "'terminator.desktop'"
      - "'gnome-system-monitor.desktop'"
    firefox_profiles:
      default:
        extensions:
          # URL on addons.mozilla.org
          - startpage-private-search
          - ublock-origin
          - i-dont-care-about-cookies
        # Privacy friendly settings reference: https://github.com/arkenfox/user.js/blob/master/user.js
        preferences:
          browser.aboutConfig.showWarning: false
          browser.discovery.enabled: false                                             # Disable "Recommend extensions / features as you browse"
          browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons: false
          browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features: false
          # Privacy - Safe browsing
          browser.safebrowsing.downloads.enabled: false
          browser.safebrowsing.downloads.remote.block_potentially_unwanted: false
          browser.safebrowsing.downloads.remote.block_uncommon: false
          browser.safebrowsing.malware.enabled: false
          browser.safebrowsing.phishing.enabled: false
#          browser.shell.checkDefaultBrowser: false
          browser.toolbars.bookmarks.visibility: 'always'                              # Show bookmarks bar (always, newtab, never)
          browser.startup.page: 1                                                      # 0=blank, 1=home (DEFAULT), 2=last visited page, 3=resume previous session
          browser.startup.homepage: "{{ 'https://ipleak.net/' if 'il_workstations' in group_names else 'about:home' }}"
          browser.newtabpage.enabled: true
          browser.newtab.preload: false
          browser.newtabpage.activity-stream.feeds.telemetry: false
          browser.newtabpage.activity-stream.telemetry: false
          browser.newtabpage.activity-stream.feeds.snippets: false
          browser.newtabpage.activity-stream.feeds.section.topstories: false
          browser.newtabpage.activity-stream.section.highlights.includePocket: false
          browser.newtabpage.activity-stream.showSponsored: false
          browser.newtabpage.activity-stream.feeds.discoverystreamfeed: false
          browser.newtabpage.activity-stream.showSponsoredTopSites: false
          browser.newtabpage.activity-stream.default.sites: ''
          browser.newtabpage.activity-stream.feeds.section.topstories.options: ''
          dom.gamepad.enabled: false
          dom.vr.enabled: false
          dom.vibrator.enabled: false
          extensions.pocket.enabled: false
          extensions.pocket.api: ''
          extensions.pocket.oAuthConsumerKey: ''
          extensions.pocket.site: "''"
          geo.provider.network.url: "https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%"
          geo.provider.ms-windows-location: false                                      # Windows
          geo.provider.use_corelocation: false                                         # Mac
          geo.provider.use_gpsd: false                                                 # Linux
          browser.region.network.url: ''
          browser.region.update.enabled: false
          intl.accept_languages: 'en-US, en'
          javascript.use_us_english_locale: true
          extensions.getAddons.showPane: false
          extensions.htmlaboutaddons.recommendations.enabled: false
          datareporting.policy.dataSubmissionEnabled: false
          datareporting.healthreport.uploadEnabled: false
          toolkit.telemetry.unified: false
          toolkit.telemetry.enabled: false
          toolkit.telemetry.server: 'data:,'
          toolkit.telemetry.archive.enabled: false
          toolkit.telemetry.newProfilePing.enabled: false
          toolkit.telemetry.shutdownPingSender.enabled: false
          toolkit.telemetry.updatePing.enabled: false
          toolkit.telemetry.bhrPing.enabled: false
          toolkit.telemetry.firstShutdownPing.enabled: false
          toolkit.telemetry.coverage.opt-out: true
          toolkit.coverage.opt-out: true
          toolkit.coverage.endpoint.base: ''
          browser.ping-centre.telemetry: false
          app.shield.optoutstudies.enabled: false
          app.normandy.enabled: false
          app.normandy.api_url: ''
          breakpad.reportURL: ''
          browser.tabs.crashReporting.sendReport: false
          browser.crashReports.unsubmittedCheck.autoSubmit2: false
          browser.safebrowsing.downloads.remote.enabled: false
#          browser.places.speculativeConnect.enabled: false
          browser.fixup.alternate.enabled: false                                       # disable location bar domain guessing
          browser.search.suggest.enabled: false                                        # location bar
          browser.urlbar.suggest.searches: false
          browser.urlbar.speculativeConnect.enabled: false
          browser.urlbar.suggest.quicksuggest.nonsponsored: false
          browser.urlbar.suggest.quicksuggest.sponsored: false
          browser.formfill.enable: false                                               # Search & form history
          extensions.formautofill.addresses.enabled: false                             # Autofill
          extensions.formautofill.available: 'off'
          extensions.formautofill.creditCards.available: false
          extensions.formautofill.creditCards.enabled: false
          extensions.formautofill.heuristics.enabled: false
          signon.rememberSignons: false                                                # disable auto-filling username & password form fields
          signon.autofillForms: false
#          security.ssl.require_safe_negotiation: true
#          security.tls.enable_0rtt_data: false
          beacon.enabled: false
          privacy.sanitize.sanitizeOnShutdown: true
          privacy.clearOnShutdown.cache: true
          privacy.clearOnShutdown.downloads: true
          privacy.clearOnShutdown.formdata: true
          privacy.clearOnShutdown.history: true
          privacy.clearOnShutdown.sessions: true
          privacy.clearOnShutdown.offlineApps: false
          privacy.resistFingerprinting: true
          privacy.resistFingerprinting.block_mozAddonManager: true
          browser.messaging-system.whatsNewPanel.enabled: false

- hosts: dev_workstations
  become: true
  roles:
    - role: workstation/dev_workstation
      tags:
        - dev_workstation
    - role: docker
      tags:
        - docker
  vars:
    gnome_wallpaper: win10-jobs.jpg
    firefox_profiles:
      default:
        extensions:
          - umatrix
          - darkreader
          - save-page-we

- hosts: il_workstations
  become: true
  roles:
    - role: workstation/il_workstation
      tags:
        - il_workstation
  vars:
    firefox_profiles:
      default:
        extensions:
          # URL on addons.mozilla.org
          - video-downloader-profession
          - video-downloadhelper
          - buster-captcha-solver


- hosts: servers, dev_servers, home_servers
  become: true
  roles:
    - role: server/base
      tags:
        - server
        - home_server
    - role: docker
      tags:
        - docker

- hosts: dev_servers
  roles:
    - role: server/dev_server
  tags:
    - dev_server

- hosts: home_servers
  vars:
    docker_container_data_basedir: /home/{{ user_name }}/homeserver_data/container_data
    docker_container_config_basedir: /home/{{ user_name }}/homeserver_config/container_config
  roles:
    - role: server/home_server/base
    - role: server/home_server/containers/bitwarden
      tags:
        - bitwarden
    - role: server/home_server/containers/nginx-helloworld
      tags:
        - testing
    - role: server/home_server/containers/pihole
      tags:
        - pihole
    - role: server/home_server/containers/portainer
      tags:
        - portainer

# KEEP IN MIND: Only run samba - OR - filebrowser (otherwise weird behvaior when using simultaneously)
    - role: server/home_server/containers/filebrowser
      tags:
        - filebrowser
    - role: server/home_server/containers/samba
      tags:
        - samba

    - role: server/home_server/containers/traefik
      tags:
        - traefik
    - role: server/home_server/containers/transmission
      tags:
        - transmission
    - role: server/home_server/containers/volact
      tags:
        - volact
    - role: server/home_server/containers/watchtower
      tags:
        - watchtower
  tags:
    - home_server
