---
- hosts: all
  become: true
  roles:
    - role: base
      tags:
        - base

- hosts: rpis
  become: true
  roles:
    - role: rpi
      tags:
        - rpi

- hosts: vmware_vms
  become: true
  roles:
    - role: vmware
      tags:
        - vmware

- hosts: workstations
  become: true
  roles:
    - role: workstation
      tags:
        - workstation

- hosts: servers
  become: true
  roles:
    - role: server
      tags:
        - server
        - homeserver
    - role: docker
      tags:
        - docker
        - server
        - homeserver

- hosts: homeservers
  roles:
    - role: homeserver/containers/bitwarden
      tags:
        - homeserver
        - rpi
        - bitwarden
    - role: homeserver/containers/filebrowser
      tags:
        - homeserver
        - rpi
        - filebrowser
    - role: homeserver/containers/portainer
      tags:
        - homeserver
        - portainer
    - role: homeserver/containers/traefik
      tags:
        - homeserver
        - rpi
        - traefik
    - role: homeserver/containers/watchtower
      tags:
        - homeserver
        - rpi
        - watchtower
