---
- name: 'Delete default pi user passwordless file  (TODO: Check whether newer versions still use username "pi" in filename)'
  ansible.builtin.file:
    state: absent
    path: /etc/sudoers.d/010_pi-nopasswd
  become: true


- ansible.builtin.include_tasks: '{{ item }}'
  loop:
    - usb-boot.yml
    - rpi-fan-pwm.yml



- name: '[Ubuntu] Pi specific SW'
  ansible.builtin.apt:
    name:
      - rpi-eeprom                                      # TODO: not tested yet  (see https://askubuntu.com/questions/1253070/raspberry-pi-4-firmware-upgrade-eeprom-over-ubuntu-20-04)
    state: present
  when: ansible_facts.distribution == 'Ubuntu'
  become: true
