---
- name: '[Raspberry Pi OS] Delete default pi user passwordless file  (TODO: Check whether newer versions still use username "pi" in filename)'
  ansible.builtin.file:
    state: absent
    path: /etc/sudoers.d/010_pi-nopasswd
  when: ansible_facts.distribution == 'Debian'
  become: true


- ansible.builtin.include_tasks: '{{ item }}'
  loop:
    - usb-boot.yml
    - rpi-fan-pwm.yml


- name: "Disable LEDs  (NOTE: WILL TAKE EFFECT AFTER SYSTEM REBOOT !!)"
  ansible.builtin.blockinfile:
    insertafter: '^[pi4]$'
    block: |
      # Disable Activity LED
      dtparam=act_led_trigger=none
      dtparam=act_led_activelow=off

      # Disable PWR LED  (currently not working properly  ??, see: https://stackoverflow.com/a/71492090)
      dtparam=pwr_led_trigger=default-on
      dtparam=pwr_led_activelow=off

      # Disable ethernet port (ACT & LNK) LEDs
      dtparam=eth_led0=4
      dtparam=eth_led1=4
    path: /boot/config.txt
  become: true


- name: '[Ubuntu] Pi specific SW'
  ansible.builtin.apt:
    name:
      - rpi-eeprom                                      # TODO: not tested yet  (see https://askubuntu.com/questions/1253070/raspberry-pi-4-firmware-upgrade-eeprom-over-ubuntu-20-04)
    state: present
  when: ansible_facts.distribution == 'Ubuntu'
  become: true
