---
- name: 'Delete default pi user passwordless file  (TODO: Check whether newer versions still use user "pi")'
  become: true
  ansible.builtin.file:
    state: absent
    path: /etc/sudoers.d/010_pi-nopasswd

- include_tasks: '{{ item }}'
  loop:
    - usb-boot.yml
    - rpi-fan-pwm.yml
