---
# !!  IMPORTANT: We cannot simply check for the image and skipt this step since we need the compose file  !!
- name: Clone repo
  ansible.builtin.git:
    repo: https://github.com/therealthingy/rpi-pwm.git
    dest: '{{ rpi_fan_pwm_container_dir }}'
    clone: true
    depth: 1
    update: true
  register: repo_clone
  failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in the destination' in repo_clone.msg
  become: false

- name: Change config
  ansible.builtin.lineinfile:
    dest: '{{ rpi_fan_pwm_container_dir }}/.env'
    regexp: '^UPDATE_INTERVAL_SEC=3$'
    line: 'UPDATE_INTERVAL=6'
  become: false

- name: Ensure container is running
  community.docker.docker_compose:
    project_src: '{{ rpi_fan_pwm_container_dir }}'
    build: true
  become: false
