---
# !!  IMPORTANT: We cannot simply check for the image and skipt this step since we need the compose file  !!
- name: Clone repo
  ansible.builtin.git:
    repo: https://github.com/therealthingy/rpi_fan_controller
    dest: '{{ rpi_fan_pwm_container_dir }}'
    clone: true
    depth: 1
    update: true
  register: repo_clone
  failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in the destination' in repo_clone.msg
  become: false

- name: Copy files
  ansible.builtin.copy:
    src: '{{ rpi_fan_pwm_container_dir }}/testing/{{ rpi_fan_file.file }}'
    dest: '{{ rpi_fan_file.dest_dir }}/{{ rpi_fan_file.file }}'
    owner: 'root'
    group: 'root'
    mode: 0755
    remote_src: true
  with_items:
    - { 'dest_dir': '/usr/local/bin', 'file': 'fan_control' }
    - { 'dest_dir': '/etc/systemd/system', 'file': 'fan_control.service' }
  loop_control:
    loop_var: rpi_fan_file
  become: true



# REMOVAL of SERVICE:
#  systemctl stop [servicename]
#  systemctl disable [servicename]
#  rm /etc/systemd/system/[servicename]
#  rm /etc/systemd/system/[servicename] # and symlinks that might be related
#  rm /usr/lib/systemd/system/[servicename]
#  rm /usr/lib/systemd/system/[servicename] # and symlinks that might be related
#  systemctl daemon-reload
#  systemctl reset-failed
- name: Enable service
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: fan_control
  become: true
