---
- include_tasks: local-static-ipv6-addr.yml


- name: Ensure data dir exists
  ansible.builtin.file:
    path: '{{ pihole_data_dir }}/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - hole
    - dns
#  become: true             # REQUIRED since container runs as root

- name: Create config dir
  ansible.builtin.file:
    path: '{{ pihole_config_dir }}'
    state: directory
    mode: 0755
  become: false

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ pihole_config_dir }}/docker-compose.yml'
    mode: 0640
  become: false

- name: Ensure container is running
  community.docker.docker_compose:
    project_src: '{{ pihole_config_dir }}'
    build: false
  become: false
