---
# KEEP IN MIND:
#  - PACKAGE NAMES: 'isc-dhcp-client' (`dhclient`)   !=   'dhcpcd5'    (see: https://superuser.com/questions/393887/dhclient-and-dhcpcd-the-real-difference)
#  - DNS entries here affect name resolution captabilities of docker containers !!  (containers 'inherit' config from host)
# dhcpcd5 config reference: https://manpages.ubuntu.com/manpages/trusty/man5/dhcpcd.conf.5.html
# Monitor logs (what dhcpcd does): `journalctl -u dhcpcd`
- name: "[dhcpcd5] Add static DNS entries + static IPv6 ULA addr"
  # Equivalent command (for adding IPv6 address): `sudo ip addr add {{ dns_ipv6_ula }} dev {{ dns_iface }}`
  # Validate (show ip addresses): `ip -6 address show dev eth0`
  ansible.builtin.blockinfile:
    block: |
      interface {{ dns_iface }}
      static domain_name_servers={{ dns_server1_ipv4 }} {{ dns_server1_ipv6 }} {{ dns_server2_ipv4 }} {{ dns_server2_ipv6 }}
      static ip6_address={{ dns_ipv6_ula }}
    path: /etc/dhcpcd.conf
  notify: restart dhcpcd service
  become: true



- name: Create config dir
  ansible.builtin.file:
    path: '{{ pihole_config_dir }}'
    state: directory
    mode: 0755
  become: false

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ pihole_config_dir }}/docker-compose.yml'
    mode: 0640
  become: false

- name: Ensure container is running
  community.docker.docker_compose:
    project_src: '{{ pihole_config_dir }}'
    build: false
  become: false
